### ISSUE TITLE
makems doesn't compile, but do we need it?

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#103]
reported upstream: https://github.com/ska-sa/makems/issues/3

Do we still need it? Probably not? There is a `makems` in the lofar package, and casacore now also comes with a `writems` command:

https://manpages.debian.org/testing/casacore-tools/writems.1.en.html

**Comment by o-smirnov** [comment]
> gijzelaerr assigned o-smirnov and unassigned o-smirnov 2 hours ago

Am I Schroedinger's assignee?

I think the ``meqtrees-cattery`` test still uses ``makems``. But only the test, not the package itself. So I don't know what's easier, change the test to use ``lofar``, or make a one-liner fix to the package?

**Comment by gijzelaerr** [comment]
I prefer to switch to `lofar` package since `makems` and `lofar` are the only packages that are confliction with eachother in KERN.

**Comment by gijzelaerr** [comment]
proposed change https://github.com/ska-sa/meqtrees-cattery/pull/81

**Comment by tammojan** [comment]
Also, @sjperkins created some measurement creation functionality in python-casacore, see casacore/python-casacore/pull/72 . Might be useful here.

**Comment by gijzelaerr** [comment]
yeah i've seen, thanks. it is just the path of least resistance to switch to lofar for now.

**Comment by gijzelaerr** [comment]
ok well i'm going to close this issue, since there are plenty alternatives available. If the old `makems` is required @Athanaseus should fix it.

**Comment by sjperkins** [comment]
> Also, @sjperkins created some measurement creation functionality in python-casacore, see casacore/python-casacore/pull/72 . Might be useful here.

I've started putting together a python package based on this added functionality, but have yet to finalise or release it. The intention is to create MS's for testing purposes.

**Comment by tammojan** [comment]
Note that recently casacore got a `writems` tool, quite similar to lofar's `makems`. See [here](https://github.com/casacore/casacore/pull/653)
