### ISSUE TITLE
AIPS kern-3 permission errors

### ISSUE THREAD

**Issue by IanHeywood** [kernsuite/packaging#112]
I get permission errors that prevent me from running AIPS (via runaips) unless I'm root. Not sure if I'm missing something here.

Thanks.

**Comment by gijzelaerr** [comment]
did you add yourself to the aips group?

**Comment by IanHeywood** [comment]
I did now!

Thanks.

**Comment by gijzelaerr** [comment]
So usually this kind of info can be found in the README.Debian in the package documenation folder
(`/usr/share/doc/aips/README.Debian`). But in this case this info was missing, added: https://github.com/kernsuite-debian/aips/commit/8f72709625e3e03151e69f7e3ca887b8e79058b8
