### ISSUE TITLE
Unable to install pybdsf on Ubuntu 18.04

### ISSUE THREAD

**Issue by Kitchi** [kernsuite/packaging#116]
I'm using the kern-4 repo for Ubuntu 18.04, but when I try to 

`sudo apt install pybdsf`

I get the following error

> The following packages have unmet dependencies:
>  pybdsf : Depends: python-pywcs but it is not installable
> E: Unable to correct problems, you have held broken packages.

This seems to be because the default python on Ubuntu 18.04 is python 3, and python-pywcs is exclusively python 2. Are there any workarounds for this issue?

**Comment by gijzelaerr** [comment]
should be fixed in `pybdsf_1.8.14-1kern3`
