### ISSUE TITLE
package up heasoft

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#12]
x-ray people will be happy

http://heasarc.nasa.gov/lheasoft/

**Comment by gijzelaerr** [comment]
heasoft is just such a disaster to package as like casa, probably only a docker image will work out.

**Comment by olebole** [comment]
I tried to contact them a few years ago, and they at least wanted to consider packaging it themself.
It may be worth if they would get another request for this from a different person :-)

**Comment by gijzelaerr** [comment]
sure, but heasoft is quite out of off scope for me.

**Comment by gijzelaerr** [comment]
looking at their structure, it will take quite some effort to unravel. I prefer not to get involved with that, those things eat mountains of time.

**Comment by gijzelaerr** [comment]
this is just too much out of scope and too much work, i have to cancel this.

**Comment by olebole** [comment]
Could you anyway contact them and express your interest having Debian package here? If this not only comes from me, it may help them to see a need :-)

Another point: Heasoft is quite modular. Until they (or someone else) does a complete packaging, it may be worth to cherrypick just the packages that are requested. We already have [cfitsio](https://packages.debian.org/source/unstable/cfitsio), [fv](https://packages.debian.org/source/unstable/ftools-fv), [fitsverify](https://packages.debian.org/source/unstable/fitsverify), and [fitstcl](https://packages.debian.org/source/unstable/tcl-fitstcl). Do you have a list what people want?

**Comment by gijzelaerr** [comment]
Our group is not interested in heasoft. I was in washington DC a couple of months ago where somebody mentioned it, so I had a quick look and then decided it is too much work for now for a project i'm not involved in. Please sent me an email with their contact information, then Ill write them a message saying that we also have interest packaging it up, since that seems to maybe move things forward.

**Comment by olebole** [comment]
Probably Bryan Irby <bryan.k.irby@nasa.gov> is the right person here. When I asked for a Debian package in May 2015, he responded that they want to package it (but needed some advise how to do it). After I have sent some instructions, he didn't answer, however. Maybe you could also address ftoolshelp@bigbang.gsfc.nasa.gov .
