### ISSUE TITLE
meqtrees-timba should depend on netbase

### ISSUE THREAD

**Issue by bmerry** [kernsuite/packaging#124]
I'm not sure which of the timba packages (meqtrees-timba or libmeqtrees-timba0) is the one that needs the dependency added, but [this line](https://github.com/ska-sa/meqtrees-timba/blob/a86161a2ceb1c27b18de3aa4f65525d2a204c5c8/TimBase/src/Net/Socket.cc#L391) fails if /etc/protocols is missing, which is provided by netbase.

I'm using KERN-3 and Ubuntu 16.04; haven't checked the situation on KERN-4 / 18.04.

**Comment by gijzelaerr** [comment]
added netbase dependency to `libmeqtrees-timba0`, uploaded to kern-dev.
