### ISSUE TITLE
python-casacore dependency libcasa-derivedmscal2

### ISSUE THREAD

**Issue by ygrange** [kernsuite/packaging#125]
I am trying to run the InitSubtract_deep_sort_and_compute step from prefactor. In this step, a taql command is executed via pyrap.tables (essentially python-casacore). If I install everything via kern, the script crashes because it depends on libcasa_derivedmscal.so. This is fixed by installing the libcasa-derivedmscal2 package. Could you make that a dependency of python-casacore?

**Comment by gijzelaerr** [comment]
can you show me the taql command and the error?

**Comment by ygrange** [comment]
It's basically this line in the prefactor repo that triggers it:

https://github.com/lofar-astron/prefactor/blob/c3b3a8664c2e2c16b4c5f86a8bd1b1763207502a/scripts/InitSubtract_deep_sort_and_compute.py#L63

So if for any reason it shouldn't be considered a dependency for python-casacore, it certainly is a dependency for prefactor.

**Comment by gijzelaerr** [comment]
ok since you are calling a mscal function from prefactor i have the opinion it is a dependency for prefactor.

**Comment by gijzelaerr** [comment]
added dependcy to prefactor and uploaded to kern-dev.
