### ISSUE TITLE
Package up APSYNSYM

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#127]
This is a very cool learning tool. https://launchpad.net/apsynsim. Pure Python, I think.

**Comment by tammojan** [comment]
I had to update quite a bit to get it running under python3 with modern tkinter etc. Here's the [patch](https://gist.github.com/tammojan/c330676515ae46d2a9cbdc76fd090a69) (also e-mailed to Ivan, I have no idea how to do a pull request in bazaar/launchpad).

**Comment by gijzelaerr** [comment]
yeah, pure python but hard coded paths so no that trivial to package.

**Comment by gijzelaerr** [comment]
packaged and uploaded to kern-dev and kern-4. didn't convert to py3 though, but looks like that is not required to get it running.
