### ISSUE TITLE
Add tensorflow package

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#129]
looks like it is going somewhere

https://github.com/tensorflow/tensorflow/pull/21699

**Comment by gijzelaerr** [comment]
a cpu only version of tensorflow landed in Debian https://salsa.debian.org/science-team/tensorflow

it uses a lot of Ubuntu18.04+ packages though, so a lot of backporting would be required.

**Comment by sjperkins** [comment]
> it uses a lot of Ubuntu18.04+ packages though, so a lot of backporting would be required.

Backporting to 16.04?

**Comment by gijzelaerr** [comment]
no, to ubuntu 18.04, it depends on packages that are not in ubuntu 18.04 but only in later versions

**Comment by gijzelaerr** [comment]
I think i'm just going to give up on this effort.
