### ISSUE TITLE
parseltongue can't be uploaded to kern-dev

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#132]
a version has already been uploaded but the original tarball has been deleted.

**Comment by gijzelaerr** [comment]
for parceltongue that is 2.3 and sourcery 1.2.6

**Comment by gijzelaerr** [comment]
up to today, No release has been made

https://github.com/radio-astro/sourcery
http://www.jive.nl/parseltongue/releases/

**Comment by gijzelaerr** [comment]
i've made a new release for sourcery: https://github.com/radio-astro/sourcery/releases/tag/1.2.7

**Comment by gijzelaerr** [comment]
it looks like parceltongue has a new release http://www.jive.nl/parseltongue/releases/parseltongue-3.0.tar.gz

@Athanaseus can you have a look at that?

**Comment by Athanaseus** [comment]
The latest parseltongue has been uploaded to KERN-dev and KERN-7.

**Comment by gijzelaerr** [comment]
you are a hero!
