### ISSUE TITLE
Unable to locate package gsm

### ISSUE THREAD

**Issue by sarrvesh** [kernsuite/packaging#141]
I am trying to install the package gsm within Kern-4 however when I do sudo apt-get install gsm, I get E: Unable to locate package gsm. Other packages like lofar and losoto worked fine. Could you please have a look?

**Comment by gijzelaerr** [comment]
the package name is `python-gsm` or `python3-gsm` if you use python3.

You can see that on the package list on the website:

http://kernsuite.info/packages/

The binary packages names are listed there.
