### ISSUE TITLE
add codex africanus

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#149]
https://codex-africanus.readthedocs.io/

**Comment by sjperkins** [comment]
We need to do a release but I think that would only happen when we've sorted out issues with the gridder, convolution filter and taper /cc @landmanbester

**Comment by gijzelaerr** [comment]
so how is this new release getting along @sjperkins

**Comment by sjperkins** [comment]
@landmanbester What do you think of the state of the gridding code? We could also just move it all into an experimental package for the release and keep on devving there if it's not currently ready.

**Comment by landmanbester** [comment]
The gridder is not ready for release yet so let's maybe pull it out for now

**Comment by gijzelaerr** [comment]
@sjperkins shall i just add 0.1.4?

**Comment by sjperkins** [comment]
Yes, add 0.1.4 I think. Note that there are lots of optional dependencies that are not installed by default. You may want to support all of them?

**Comment by gijzelaerr** [comment]
I have a package for codex africanus now, but it looks like it requires a numba ` >= 0.46.0':
https://github.com/ska-sa/codex-africanus/blob/master/africanus/install/requirements.py#L23

Bionic comes with 0.34.0-3
https://packages.ubuntu.com/bionic/python-numba

So yeah, this is not going to work, unless africanus adds support for the older numba, or we have to wait for including it for KERN-7 (if that is going to be based on ubuntu focal / 20.04)

**Comment by sjperkins** [comment]
Looking back over this, I don't think a debian package is worth the effort, considering the fast cadence of codex-africanus releases.

To me, this implies replicating the pypi packaging structure in Debian. Unless the underlying pypi dependency changes are updated, I think there'll be one release on KERN-7 that quickly becomes out of date.

This is because with each new release, codex-africanus/dask-ms depends on newer numba/dask/python-casacore releases. The first two also iterate quickly.

Additionally, as python-casacore now has binary wheels, dask-ms, as well as applications built on it are easily pip installable.

**Comment by gijzelaerr** [comment]
If you want codex africanus to be a stable building block for other software packages, a Debian package is not a bad idea.

**Comment by sjperkins** [comment]
OK, lets scope the required work.

I think it would involve making custom kernsuite Debian packages (i.e. override base packages) for the following python dependencies:

https://github.com/ska-sa/codex-africanus/blob/master/africanus/install/requirements.py#L15-L34

and then being able to keep them up to date. Is that a reasonable or challenging goal?

**Comment by gijzelaerr** [comment]
In my experience, as a library matures the need for the latest and greatest slows down. If it does not, it is not a stable framework where you can rely on as a solid building block. I have it working for focal now, I suggest to keep it that way. If that is too much work, then it is what it is.

**Comment by sjperkins** [comment]
The APIs are stable.

The underlying implementations benefit from improvements in the dependent libraries. numba 0.46.0 adds function inlining support that has [accelerated](https://github.com/ska-sa/codex-africanus/pull/159#issuecomment-548283142) the underlying code. The addition of first class functions in numba > 0.49 has implications in https://github.com/ska-sa/codex-africanus/issues/184.

Furthermore, improvements in dask's [ordering](https://github.com/dask/dask/pull/5872) logic should benefit all dependencies.

For these reasons, I don't currently see benefits of a debian package (certainly not for bionics numba 0.34!)

**Comment by gijzelaerr** [comment]
closing this issue, the dependencies are too 'new' for ubuntu 20.04 :)
