### ISSUE TITLE
add Miriad

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#152]
http://www.atnf.csiro.au/computing/software/miriad/

**Comment by tammojan** [comment]
Note that for WSRT-data, you need a patched version, see https://www.astron.nl/radio-observatory/astronomers/analysis-wsrt-data/miriad-and-wsrt/miriad-and-wsrt (and dead links therein).

**Comment by gijzelaerr** [comment]
uploaded to KERN-dev.
