### ISSUE TITLE
python-astlib missing dependency on python-astropy

### ISSUE THREAD

**Issue by bmerry** [kernsuite/packaging#158]
After upgrading my machine to Ubuntu 18.04 and KERN-4, I get this error running tigger:
```$ tigger
Welcome to Tigger 1.4.0
Please wait a second while the GUI starts up.
Failed to import the astLib.astWCS and/or PyWCSTools module. Please install the astLib package (http://astlib.sourceforge.net/).
Traceback (most recent call last):
  File "/usr/bin/tigger", line 91, in <module>
    import TigGUI.MainWindow
  File "/usr/lib/python2.7/dist-packages/TigGUI/MainWindow.py", line 43, in <module>
    from Tigger.Models import SkyModel
  File "/usr/lib/python2.7/dist-packages/Tigger/Models/SkyModel.py", line 32, in <module>
    from Tigger.Coordinates import angular_dist_pos_angle,DEG
  File "/usr/lib/python2.7/dist-packages/Tigger/Coordinates.py", line 62, in <module>
    from astLib.astWCS import WCS
  File "/usr/lib/python2.7/dist-packages/astLib/astWCS.py", line 27, in <module>
    from astropy.io import fits as pyfits
ImportError: No module named astropy.io
```

It looks like python-astlib depends on `python-astropy | python-pyfits` (and I had only python-pyfits installed). However, grepping the astLib install I see
```python
astImages.py:from astropy.io import fits as pyfits    
astPlots.py:import pyfits
astWCS.py:from astropy.io import fits as pyfits
```
so it seems to be depending on both.

**Comment by gijzelaerr** [comment]
thanks, will have a look soon.

**Comment by gijzelaerr** [comment]
astlib is not part of KERN but debian/ubuntu

https://salsa.debian.org/debian-astro-team/astlib

I can backport a newer version, but I prefer not to. Probably best to add a  python-astropy dependency to tigger.

**Comment by gijzelaerr** [comment]
i've added an astropy dep to tigger, this will at some point land in KERN-dev and KERN-5. I decided not to change the package in KERN-4 since it is not worth the effort.

https://github.com/kernsuite-debian/tigger/commit/31b01000f2c1d101a6611395096605f1116d7ce5
