### ISSUE TITLE
request to add eht-imaging package

### ISSUE THREAD

**Issue by rdeane** [kernsuite/packaging#159]
...which can be found here: https://github.com/achael/eht-imaging

Thanks!

**Comment by gijzelaerr** [comment]
@Athanaseus how is this going? any progress? are you stuck?

**Comment by Athanaseus** [comment]
I got a bit distructed on this one, but I'll carry on right away. Thanks.

**Comment by rdeane** [comment]
NFFT may be the stumbling block here.

**Comment by Athanaseus** [comment]
How about using the Python bindings for the NFFT3 library, `python-pynfft`?

**Comment by rdeane** [comment]
worth a try...

**Comment by gijzelaerr** [comment]
didn't we try that yesterday, and those seem to work right @Athanaseus

**Comment by Athanaseus** [comment]
Yes, it worked.

**Comment by gijzelaerr** [comment]
eht-imaging has been uploaded to KERN-4, KERN-5 and KERN-dev. Thanks @Athanaseus !

**Comment by rdeane** [comment]
awesome, thanks all!
