### ISSUE TITLE
Recipies for a few packages

### ISSUE THREAD

**Issue by bennahugo** [kernsuite/packaging#16]
Okay so per conversation earlier we could theoretically create debian packages for a few more packages. These are the docker recipes I've made for 3GCIV (a bit patchy but all there):
https://github.com/bennahugo/3GCIV_Docker

There is also a fix in there for the NRAO CASA docker image. With the help of Eric Greisen and Tom Mauch I've got AIPS along with the TV going as well. The .bashrc contains the lines necessary to run these packages with X11 support.

**Comment by gijzelaerr** [comment]
So the packages that dont have a debian package are:

- [x] karma http://www3.nd.edu/~iraf/Public/karma/www/ftp.html
- [ ] miriad
- [x] aips
- [ ] fat
- [ ] gipsy
- [ ] mirad_umd
- [ ] sofia
- [x] tirific

**Comment by gijzelaerr** [comment]
tirific is now in KERN-2 and KERN-dev

**Comment by gijzelaerr** [comment]
karma is now in KERN-2 and KERN-dev

**Comment by gijzelaerr** [comment]
aips is now part of KERN-2 and KERN-dev

**Comment by gijzelaerr** [comment]
@bennahugo I'm getting a lot of compile errors for miriad, any idea?

```
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `cogetd_':
co.f:(.text+0x2a73): undefined reference to `celgtd_'
co.f:(.text+0x2acd): undefined reference to `celgtd_'
co.f:(.text+0x2b25): undefined reference to `celgtd_'
co.f:(.text+0x2b72): undefined reference to `celgtd_'
co.f:(.text+0x2bc9): undefined reference to `celgti_'
co.f:(.text+0x2be5): undefined reference to `prjgtd_'
co.f:(.text+0x2c3a): undefined reference to `spcgtd_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `cofindax_':
co.f:(.text+0x2e85): undefined reference to `spcgtd_'
co.f:(.text+0x2eb1): undefined reference to `spcgtc_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `coll2xy_':
co.f:(.text+0x3117): undefined reference to `celgti_'
co.f:(.text+0x3138): undefined reference to `prjgtc_'
co.f:(.text+0x3164): undefined reference to `celgtd_'
co.f:(.text+0x3270): undefined reference to `cels2x_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `coxy2ll_':
co.f:(.text+0x33e7): undefined reference to `celgti_'
co.f:(.text+0x3408): undefined reference to `prjgtc_'
co.f:(.text+0x3430): undefined reference to `celgtd_'
co.f:(.text+0x34dc): undefined reference to `celx2s_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `cocel_':
co.f:(.text+0x3b51): undefined reference to `celgtd_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `cocreate_':
co.f:(.text+0x4ade): undefined reference to `celini_'
co.f:(.text+0x4af9): undefined reference to `spcini_'
/home/gijs/packaging/miriad/linux64/lib/libmir.a(co.o): In function `coreinit_':
co.f:(.text+0x4c40): undefined reference to `wcserr_enable_'
co.f:(.text+0x5064): undefined reference to `celptd_'
co.f:(.text+0x5083): undefined reference to `celptd_'
co.f:(.text+0x509d): undefined reference to `celgti_'
co.f:(.text+0x513e): undefined reference to `prjptc_'
```

**Comment by gijzelaerr** [comment]
FAT just looks to beta to even consider packaging.

**Comment by gijzelaerr** [comment]
@bennahugo what is wrong with sofia 1.0?

**Comment by gijzelaerr** [comment]
@bennahugo do you even read your messages??

**Comment by gijzelaerr** [comment]
some compile notes by Laura for miriad:

I re-installed miriad on Elwood, from source and changing MAXANT to 130 in the .h files.
I added notes to the old Jake/Elwood install page here:
https://docs.google.com/document/d/1HO918OnomoAfmjjc60y5Zoi-S4scCPTadZQnS55zIv8/edit

**Comment by gijzelaerr** [comment]
i'm going to close this issue now, the remaining packages are too brittle to package up.
