### ISSUE TITLE
add carta

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#175]
https://cartavis.github.io/

**Comment by gijzelaerr** [comment]
carta package has been uploaded to KERN-dev, KERN-4 and KERN-5!

**Comment by o-smirnov** [comment]
Could you also package the remote version please? 

Although the provided tarball is nominally for RedHat/Centos, just untarring it and running it seems to work on Ubuntu 16.

**Comment by gijzelaerr** [comment]
will do

**Comment by o-smirnov** [comment]
Just note that you might need to rename the binary. In their tarball it's called ``something-remote-something/carta``, which will surely clash with the normal ``carta`` once you've got both in the path. Rename to ``carta-remote``, perhaps?

**Comment by gijzelaerr** [comment]
uploaded to kern-5 and kern-dev, should be available soon.
