### ISSUE TITLE
import astropy.io.fits fails in astropy==2.0.11

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#176]
```
In [1]: import astropy.io.fits as pyfits
   ...: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: No module named _multiarray_umath

In [2]:                                                                                                                                                                                   
```
Works fine in 2.0.10.

**Comment by o-smirnov** [comment]
Hmmm, the plot thickens. It depends on which Ubuntu.

On Ubuntu 16.04, both 2.0.10 and 2.0.11 print the error above.

On Ubuntu 18.04, 2.0.10 is OK but 2.0.11 prints the error.

(I'm trying to import it in two otherwise identical virtual environments...)

I should rather say warning, as it proceeds to run afterwards anyway.

**Comment by gijzelaerr** [comment]
I can't replicate the issue on Ubuntu 18.04, python2 and 2.0.11 (virtualenv, tshikovski)

**Comment by gijzelaerr** [comment]
this is just not a KERN issue, closing this.

**Comment by o-smirnov** [comment]
@bennahugo, I first saw this here...

**Comment by gijzelaerr** [comment]
hm?

**Comment by o-smirnov** [comment]
Seeing the same error in a different context. Still haven't figured it out.

**Comment by gijzelaerr** [comment]
did you experiment with the numpy version? Some googlin hints that this might be a numpy 1.15 issue and running 1.16 solved it.
