### ISSUE TITLE
ms2uvfits executable missing from casacore-tools

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#199]
This: https://github.com/casacore/casacore/tree/master/msfits/apps appears to be missing from ``casacore-tools``. I assume that's where it's meant to be packaged?

**Comment by gijzelaerr** [comment]
now if only @Athanaseus had some machine where he could do his packaging on.

**Comment by Athanaseus** [comment]
Doing a clean up of my pc in the mean time, I will do an upgrade (distro->18.04) by EOD. It should be ready for _KERN-dev_ packaging next week.

**Comment by gijzelaerr** [comment]
reported te bug upstream, since it is also in Debian/ubuntu: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929111

**Comment by gijzelaerr** [comment]
This package should be available in the `casacore-tools` package now.
