### ISSUE TITLE
python-tigger install fails on missing libicu52 dependency

### ISSUE THREAD

**Issue by sjperkins** [kernsuite/packaging#2]
- Xenial 16.04 system
- Add kernsuite PPA
  `bash
  $ sudo apt-get install software-properties-common
  $ sudo add-apt-repository -s ppa:kernsuite/kern-dev
  `
- Installed meqtrees-timba, python-meqtrees-cattery, python-owlcat
- Fell over on the following command

``` bash
$ sudo apt install python-tigger
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-tigger : Depends: libicu52 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by gijzelaerr** [comment]
ah, I thought I solved this one. I think I forgot to upload the package, will do.

**Comment by gijzelaerr** [comment]
new tigger is uploaded https://launchpad.net/~kernsuite/+archive/ubuntu/kern-dev/+build/10487032

**Comment by sjperkins** [comment]
Can confirm that tigger installs and runs, but now other issues pop up -- #5 and #6.
