### ISSUE TITLE
casacore-data is not being update at the moment

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#200]
The system used for updating has been compromised and has been taken offline.

**Comment by sjperkins** [comment]
What's the workaround? Download manually and untar from ftp://ftp.astron.nl/outgoing/Measures/?

**Comment by gijzelaerr** [comment]
i can push a manual update, what version are you using?

I need to come up with a more structural solution but that requires time (and KERN funding).

**Comment by sjperkins** [comment]
Thanks @gijzelaerr: kernsuite 5, bionic

**Comment by gijzelaerr** [comment]
pushed `casacore-data_20190909-000001-1.dsc` to KERN-4, 5 and dev.

**Comment by sjperkins** [comment]
\o/

**Comment by gijzelaerr** [comment]
we now have a shiny new uploading VM that will daily check for new data and upload it when available, to dev, 4, 5 and 6. Enjoy.

**Comment by sjperkins** [comment]
\o/
