### ISSUE TITLE
does tirific need to depend on pgplot5 or can it use giza?

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#203]
Pgplot has been end-of-lined and replaced by giza on modern Ubuntus. Unfortunately, one can't install both libpgplot5 and giza, they seem to be mutually exclusive.

Can we try linking tirific against giza instead of pgplot5 (i.e. install libgiza-dev for the build)? I believe it's a drop-in replacement.

**Comment by o-smirnov** [comment]
Not to mention, giza is written by @danieljprice, who I once wrote a paper with. :)

**Comment by o-smirnov** [comment]
@Athanaseus could you take a look at this?

**Comment by gijzelaerr** [comment]
so the issue that `tirific` is already packaged but pgplot sucks to use?

**Comment by o-smirnov** [comment]
Yeah. We need ``libgiza-dev`` for newer stuff, but it's mutually exclusive with pgplot5 (being a replacement). So if we can get tirific to build with the newer package, all will be good.

**Comment by gijzelaerr** [comment]
looks like something @Athanaseus could try

**Comment by Athanaseus** [comment]
Somehow I can't assign this to myself.

But, yeah sure I'll have a look at this.

**Comment by gijzelaerr** [comment]
i think you can now, upgraded your status.

**Comment by gijzelaerr** [comment]
@Athanaseus found this discussion: sabourke/ppgplot#1 . @Athanaseus can you check if tirific actually runs with the giza backend, not only compiles?

**Comment by Athanaseus** [comment]
This was tested, it works, see output example https://github.com/kernsuite-debian/tirific/pull/4.
