### ISSUE TITLE
FOUND NO DOCUMENTATION  for miriad

### ISSUE THREAD

**Issue by danieleUTS** [kernsuite/packaging#207]
Hi guys! 

I installed miriad but every time I try to use it I have troubles.

Every time I want to use a task, for example if I text in the miriad shell: "inp histo" the message is "found no documentation on task histo" 

I have this problem for all the tasks!

**Comment by gijzelaerr** [comment]
you might need to set some environment variables:
```
MIR=/usr/bin
MIRCAT=/usr/share/miriad
MIRDEF=.
MIRARCH=linux64
```
https://www.atnf.csiro.au/computing/software/miriad/userguide/node15.html

**Comment by gijzelaerr** [comment]
does this solve your issue?

**Comment by danieleUTS** [comment]
Hello,

thank you for replying me. Unfortunately, no. It looks like it is not
possible to find the libraries.

Daniele

Il giorno lun 15 lug 2019 alle ore 23:53 Gijs Molenaar <
notifications@github.com> ha scritto:

**Comment by gijzelaerr** [comment]
ok. I'm unfamiliar with miriad myself so I can't help you unless someone points out what could be the issue. I'll leave this issue open until someone has an answer.

**Comment by danieleUTS** [comment]
ok. Thank you so much for the assistance!!!

Il giorno mar 16 lug 2019 alle ore 16:08 Gijs Molenaar <
notifications@github.com> ha scritto:

**Comment by ivstog** [comment]
Adding the MIRPDOC to the environment solved the issue for me.
MIRPDOC=$MIR/doc; export MIRPDOC

**Comment by gijzelaerr** [comment]
great! Thanks! I guess we should modify the source code to point to these locations by defaul.t

**Comment by gijzelaerr** [comment]
@danieleUTS does adding the MIRPDOC environment variable solve your issue?

**Comment by gijzelaerr** [comment]
silence probably equals to problem solved.
