### ISSUE TITLE
Libraries missing from lofaruser/imaging-pipeline docker image

### ISSUE THREAD

**Issue by kagalenko-m-b** [kernsuite/packaging#214]
I am trying to run the imaging software, however both Docker and Singularity images give me the same error:

"root@839a840d903e:/# msoverview in=/opt/Data/L456104_SAP000_SB001_uv.MS verbose=T
msoverview: Version 20110407GvD
Error: Shared library lofarstman not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
libcasa_lofarstman.so.2: cannot open shared object file: No such file or directory
libcasa_lofarstman.so: cannot open shared object file: No such file or directory
liblofarstman.so.2: cannot open shared object file: No such file or directory
liblofarstman.so: cannot open shared object file: No such file or directory"

Indeed, this library is nowhere to be found in lofaruser/imaging-pipeline:latest

**Comment by gijzelaerr** [comment]
hi @kagalenko-m-b . This is not an issue with the KERN suite but with the lofar user image. Please report your error there.

https://support.astron.nl/LOFARImagingCookbook/buildlofar.html

@tammojan

**Comment by kagalenko-m-b** [comment]
I've tried to contact the help desk desk two weeks ago. Can you suggest how to contack the image maintainer(s)? Thanks

**Comment by gijzelaerr** [comment]
the LOFAR support desk should be the right entrypoint I guess. Otherwise I have no idea.

**Comment by tammojan** [comment]
The url support.astron.nl is the right place. But in this case, please just install the LofarStMan manually through https://github.com/lofar-astron/LofarStMan/ .

**Comment by kagalenko-m-b** [comment]
That's within the docker image, impossible to just install manually, would need to rebuild the whole image

**Comment by tammojan** [comment]
You can build a new docker image which derives from the cookbook one. I'll try to find your ticket and follow up through e-mail when I'm back at work.

**Comment by kagalenko-m-b** [comment]
I've tried to build image following instructions, but the build fails with C++ compile error
