### ISSUE TITLE
Installing TEMPO path issues

### ISSUE THREAD

**Issue by emmacarli** [kernsuite/packaging#215]
Good afternoon,
first of all, thank you for this great effort!

After installing TEMPO, which throws no errors, I try to run simple commands, (e.g. making polynomial coefficients : tempo -z), which throws the following error:
"Cannot open configuration file at /etc/tempo.cfg". Indeed, this file is under /etc/tempo/tempo.cfg. What should I modify to fix this path issue, please?
The command "tempo" on its own returns usage, as it should.

(I am on Ubuntu 18.04.3. As indicated, I first ran
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository -s ppa:kernsuite/kern-5
$ sudo apt-add-repository multiverse
$ sudo apt-add-repository restricted
$ sudo apt-get update
$ sudo apt-get install tempo)

**Comment by emmacarli** [comment]
If I move tempo.cfg outside the folder tempo in /etc/ , I get another path issue : "Error opening Observatory file: /build/tempo-EGK7pB/tempo-0.0~git20181219.9e3092e/obsys.dat". I don't think these folders exist. The observatory file is indeed not there but under /usr/share/tempo .
Has this do to with having to set a TEMPO environment variable?


With TEMPO2, the error "Environment variable >TEMPO2< not set" is thrown when running any command.


Adding 
TEMPO2="/usr:/usr/share/tempo2"

TEMPO="/usr:/usr/share/tempo"

to my /etc/environment did not solve the problem.

**Comment by AlexKurek** [comment]
You can try to install manually like here:
https://github.com/kernsuite/packaging/issues/208

**Comment by gijzelaerr** [comment]
Unfortunately, due to time and budget constraints we are dropping pulsar packages from KERN-6.
