### ISSUE TITLE
Package latest LOFARBeam

### ISSUE THREAD

**Issue by tammojan** [kernsuite/packaging#217]
LOFARBeam is in the process of being moved from https://github.com/lofar-astron/LOFARBeam to https://git.astron.nl/RD/LOFARBeam . Currently, the best version is still on github, but a new release on the ASTRON-git is due to be released in a few weeks. This will be needed for an upcoming DP3 release as well.

**Comment by gijzelaerr** [comment]
4.1.1 has been uploaded to KERN-dev and KERN-6 (and builds)
