### ISSUE TITLE
Package latest casacore

### ISSUE THREAD

**Issue by tammojan** [kernsuite/packaging#218]
Casacore will be updated with 64-bit support in a few weeks; the API changes are backward compatible so older software can build against the new casacore. This release will happen when https://github.com/casacore/casacore/pull/945 is merged.

**Comment by tammojan** [comment]
Would be good to check that `taql --version` reports the latest version (probably 3.3.0).

**Comment by tammojan** [comment]
Never mind, this will work. Somehow, whoever released casacore v3.0.0 forgot to update the version number in version.h:
https://github.com/casacore/casacore/blob/v3.0.0/casa/version.h

**Comment by gijzelaerr** [comment]
casacore 3.3.0 has been uploaded to KERN-6 and KERN-dev.
