### ISSUE TITLE
add ddfacet

### ISSUE THREAD

**Issue by Athanaseus** [kernsuite/packaging#228]

**Comment by gijzelaerr** [comment]
I don't  think DDfacet is in a state close to packagable...

**Comment by Athanaseus** [comment]
Some of the requirements not packaged

```
codex-africanus[dask] <= 0.1.8
configparser >= 3.7.1 (still python2)
pylru >= 1.1.0
```

**Comment by gijzelaerr** [comment]
lets just give up on ddfacet, it is close to impossible to make a debian package of ut,
