### ISSUE TITLE
Purify not working in kern-4

### ISSUE THREAD

**Issue by bellab4710** [kernsuite/packaging#247]
Hi, I saw in issue #77 that purify should be present in kern 4/dev. However, when I install either kern version and then install the purify package, it doesn't work, giving me the error message "terminate called after throwing an instance of 'casa::TableNoDatFile'
  what():  Table file /root/table.dat does not exist
Aborted (core dumped)."
Is there anything that can be done about this?

**Comment by gijzelaerr** [comment]
hi @bellab4710 

Purify is part of the normal Ubuntu 18.04 packages, also for KERN-4. But I recommend you use a later version of KERN, since KERN-4 is not actively supported anymore.
