### ISSUE TITLE
what happened to apsynsim?

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#248]
It used to be in KERN-6, but no more. Why has it been #cancelled?

**Comment by gijzelaerr** [comment]
it was just not added and nobody complained until now. @Athanaseus can you have a look? upload it to both KERN-6 and KERN-7.

**Comment by o-smirnov** [comment]
Confused why I have it installed on my laptop though. Maybe it's the case that it was in KERN-5 and just stayed installed.

Consider me complaining!

**Comment by gijzelaerr** [comment]
here is a list of other packages that didn't make it to KERN-6 https://github.com/kernsuite/packaging/issues/226

please open an issue if you see something that is important

**Comment by o-smirnov** [comment]
So the checked checkboxes are the ones that **have** made it into KERN-6?

**Comment by Athanaseus** [comment]
> it was just not added and nobody complained until now. @Athanaseus can you have a look? upload it to both KERN-6 and KERN-7.

Yeah, I'm looking into this. I got this description on the website 'Source code. Please, run on Python 2.7 and install any missing dependency.' If this means it only runs python2 this is an issue for KERN-7.
https://launchpad.net/apsynsim/+download

**Comment by Athanaseus** [comment]
> So the checked checkboxes are the ones that have made it into KERN-6?

Yes, that's correct.

**Comment by o-smirnov** [comment]
> If this means it only runs python2 this is an issue for KERN-7.

Last I looked, there was a Python3 version in the source tree as well, so let's just check if that runs?

**Comment by Athanaseus** [comment]
OK it worked. I uploaded the new py3 upstream version `2.0b` on KERN (6,7, dev).
