### ISSUE TITLE
Missing DEP-11 48x48 Icons Kern 5

### ISSUE THREAD

**Issue by bennahugo** [kernsuite/packaging#250]
Using kern 5 as production environment at home and missing
```
Err:14 http://ppa.launchpad.net/kernsuite/kern-5/ubuntu bionic/main DEP-11 48x48 Icons                                              
  404  Not Found [IP: 91.189.95.85 80]
```
Any chance the package can be reuploaded @Athanaseus ?

**Comment by bennahugo** [comment]
I tried apt update already to refresh the lists, but still missing

**Comment by gijzelaerr** [comment]
what package are you installing?

**Comment by bennahugo** [comment]
I have a series of packages already installing I'm installing a non-kern related package and this  is one of the errors popping up when I run apt-get update. I'll see about getting a list of kern 5 packages on my system

**Comment by gijzelaerr** [comment]
KERN-5 is functioning fine, to me it looks like you have a broken apt configuration. 

```
$ docker run -ti kernsuite/base:5
# apt-get update
# apt-get install -y aoflagger
```
works fine without issues.

**Comment by gijzelaerr** [comment]
maybe should try re-adding the kern repo

https://askubuntu.com/questions/1336883/if-i-make-an-update-i-get

**Comment by bennahugo** [comment]
that actually worked. Thanks for pointing it out. never seen the apt cache corrupts like this and not fixable by update
