### ISSUE TITLE
python-casacore has no installation candidate

### ISSUE THREAD

**Issue by ifornax** [kernsuite/packaging#254]
Hi,

I followed the instructions to install python-casacore on ubuntu 20.04 and get the following error:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ sudo apt-get install python-casacore
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-casacore is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-casacore' has no installation candidate

**Comment by gijzelaerr** [comment]
do you mean python3-casacore?

**Comment by ifornax** [comment]
Yeah should be python3-casacore in the https://kernsuite.info/ info. 
It has installed now. 
Thanks

**Comment by gijzelaerr** [comment]
@Athanaseus can you update the main website to avoid this confusion?
