### ISSUE TITLE
Missing dependencies for tigger

### ISSUE THREAD

**Issue by JSKenyon** [kernsuite/packaging#256]
When attempting to install `tigger` from kern-7 on a fresh Pop!_OS 20.04 install (effectively Ubuntu), installation proceeds as normal, but attempting to run `tigger` gives the following error:

![Error](https://user-images.githubusercontent.com/6582745/153559123-2c85aaaa-0426-495b-8afe-2e002c0b0e0d.png)

**Comment by gijzelaerr** [comment]
does installing any of these packages resolve your issue? @Athanaseus I think we need to manually upload the upgraded qwt package that is in the trigger repo now, maybe I already uploaded the source package to the kern-debian repo somewhere

**Comment by JSKenyon** [comment]
I think I have managed to satisfy some of them manually now - I can run `tigger` after a reinstall. Not entirely sure what I ultimately had to install though - I think I ended up installing every qt related package I saw on the [repo](https://github.com/ska-sa/tigger).

**Comment by Athanaseus** [comment]
Thanks for the issue @JSKenyon.

> I think we need to manually upload the upgraded qwt package that is in the trigger repo now

Yes, they are already uploaded.

These requirements were not specified in the run-time dependencies.
It's fixed now, updates uploaded to _KERN_, it should be public in a bit.

`sudo apt install tigger` should now automatically install all the dependencies.

**Comment by JSKenyon** [comment]
Can confirm that this is now fixed. Thanks @Athanaseus and @gijzelaerr!
