### ISSUE TITLE
Can't install lsmtool with kern7

### ISSUE THREAD

**Issue by StFroese** [kernsuite/packaging#257]
I can't install the lsmtool with kernsuite/kern7. 
I followed the install instruction on the website
```
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository -s ppa:kernsuite/kern-7
$ sudo apt-add-repository multiverse
$ sudo apt-add-repository restricted
$ sudo apt-get update
```
### Error
```
(base) stefan@stefan-notebook:~$ sudo apt-get install lsmtool
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lsmtool : Depends: python-lsmtool but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by Athanaseus** [comment]
Thanks for the issue @StFroese.
Since we dropped python2 support this should have `python3-lsmtool` as a run-time dependency.
I have made a fix on this package.

Please try re-installing after doing `apt update.

PS: I noticed it also depends on `lofar` package, and I'm having issues compiling it.
I will update this issue once I get it to work.

**Comment by StFroese** [comment]
@Athanaseus installing `lsmtool` now works, thx. 
Is there a reason why the `lofar` package was only available until kern-5? I can't find the binary package in kern-7.

**Comment by gijzelaerr** [comment]
the lofar package has been split up and depricated. If you need the LOFAR package you are stuck with kern-5.
