### ISSUE TITLE
wsclean/libstationresponse3 broken in KERN-6?

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#259]
After an update (of an 18.04 system), I can no longer run wsclean:

```
$ sudo apt install wsclean libstationresponse3 libcasa-tables5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcasa-tables5 is already the newest version (3.4.0+5.8.0+2021.2.4-1~bionic2).
libstationresponse3 is already the newest version (4.1.1-2).
libstationresponse3 set to manually installed.
wsclean is already the newest version (2.9-2kern3).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
$ wsclean
wsclean: symbol lookup error: /usr/lib/libstationresponse.so.3: undefined symbol: _ZNK8casacore11ArrayColumnIdEclEj
```

Am I missing something, stuck on an older version of something, or is the current set of packages in the repo broken?

**Comment by gijzelaerr** [comment]
I'm quite sure something breaks with the upgrade path somehow, just to make sure you can continue what happens if you:
```
$ dpkg -P wsclean libstationresponse3 libcasa-tables5
$ apt-get autoremove
$ apt-get clean
$ apt-get update 
$ apt-get upgrade
$ apt-get install wsclean
```

**Comment by gijzelaerr** [comment]
and before you do that, what are the 14 packages that  are not upgraded and why? what do you see if you just run `apt-get dist-upgrade` now?

**Comment by o-smirnov** [comment]
> and before you do that, what are the 14 packages that are not upgraded and why

Just some updates to cups-related stuff that showed up in the past 2 hours. ``apt upgrade`` installs them.

Ah but look, when I reinstall, it pulls stuff from the CARTA PPA:
```
Get:1 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-casa5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [898 kB]
Get:2 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-tables5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [1,498 kB]
Get:3 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-measures5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [408 kB]
Get:4 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-fits5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [322 kB]
Get:5 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-scimath-f5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [179 kB]
Get:6 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-scimath5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [359 kB]                 
Get:7 http://ppa.launchpad.net/cartavis-team/carta/ubuntu bionic/main amd64 libcasa-ms5 amd64 3.4.0+5.8.0+2021.2.4-1~bionic2 [1,132 kB]                    
Get:8 http://ppa.launchpad.net/kernsuite/kern-6/ubuntu bionic/main amd64 libstationresponse3 amd64 4.1.1-2 [92.5 kB]                                       
Get:9 http://ppa.launchpad.net/kernsuite/kern-6/ubuntu bionic/main amd64 libwsclean2 amd64 2.9-2kern3 [894 kB]                                             
Get:10 http://ppa.launchpad.net/kernsuite/kern-6/ubuntu bionic/main amd64 wsclean amd64 2.9-2kern3 [19.2 kB]                                               
```
If I remove the CARTA PPA and install wsclean, everything works now.

So what happened, did the CARTA people upload casacore packages with a newer version that superceded the KERN versions? I vaguely remember we had solved this problem with them before... at least CARTA and KERN could coexist...

**Comment by o-smirnov** [comment]
As I recall, CARTA needed its own specific version of the casacore libs, but you and Adrianna sorted that out...

**Comment by Athanaseus** [comment]
> So what happened, did the CARTA people upload `casacore` packages with a newer version that superceded the KERN versions?

Yes, you are right @o-smirnov, `CARTA` and `KERN` should coexist.
Unfortunately, this is what's going on:

```
FROM kernsuite/base:6
RUN add-apt-repository ppa:cartavis-team/carta
RUN apt update
RUN apt clean
RUN apt list --all-versions libcasa-casa5
```

This gives output:
```
Listing...                                                                                                                                                                                                         
libcasa-casa5/bionic 3.4.0+5.8.0+2021.2.4-1~bionic2 amd64                                                                                                                                                          
libcasa-casa5/bionic 3.3.0-1kern1 amd64
```

This means the package still exists (**was not deleted but superseded**) on `CARTA` archive and the version is greater than that of the `KERN-6` libcasa version. When installing, the higher version always gets the priority, that's why `CARTA` version is pulled.

Here is how it looks on their repo:
![Screenshot from 2022-06-01 11-23-15](https://user-images.githubusercontent.com/16665629/171372397-d819e9db-891a-491e-ad7c-662c8bab6b28.png)
![Screenshot from 2022-06-01 11-24-21](https://user-images.githubusercontent.com/16665629/171372480-3ada48b2-5fb6-452d-aef1-529747377aa8.png)

This applies to the focal version (their KERN-7 equivalentce).

**Comment by confluence** [comment]
Apologies; I did not previously realise that the superseded packages remained installable and that there are circumstances under which they could be selected for installation. I will delete these obsolete versions from the PPA.

**Comment by o-smirnov** [comment]
Thanks @confluence -- would you let me know when you've done so, so I can retest the installations?

**Comment by confluence** [comment]
I have just requested deletion of the two packages (for focal and bionic); it may take some time for the change to be applied.

**Comment by o-smirnov** [comment]
OK looks like we're back in business -- thanks @confluence!
