### ISSUE TITLE
SPAM 

### ISSUE THREAD

**Issue by sensingcosmos** [kernsuite/packaging#36]
Hi Gijs,
              Can you please package SPAM (the help page to install SPAM is here https://safe.nrao.edu/wiki/bin/view/Main/HuibIntemaSpamInstall) so that it can be used in stimela. Thanks.

Cheers,
 Abhik

**Comment by gijzelaerr** [comment]
It looks like it depends on AIPS, which is a absolute nightmare to package so maybe, some day.

**Comment by sensingcosmos** [comment]
Yes it is based on AIPS.

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by gijzelaerr** [comment]
@radiosky-abhik it depends on AIPS version 31DEC13 but we have a 31DEC16 package now. Does it work with the newer version?

**Comment by sensingcosmos** [comment]
That's great Gijs. At least then we can install AIPS w/o any problem.

Regarding SPAM installation I am not quite sure. In the download page https://safe.nrao.edu/wiki/bin/view/Main/HuibIntemaSpamInstall Huib uses the 13 version, but I think SPAM should also work with AIPS 16 version. Huib provides other tar balls in the above link.

**Comment by gijzelaerr** [comment]
ok i dont think i'll make the spam package then, it is too brittle and fragile. I just tried to get it compiling and it seems to be working. Obit, parseltongue and aips are installed on all systems now.
