### ISSUE TITLE
libcasa_msvis.so error in lwimager, awimager, meqserver

### ISSUE THREAD

**Issue by kmbasad** [kernsuite/packaging#37]
I installed lofar and meqtrees-timba using kerne-1 ppa in Ubuntu 16.04.2. Other software like wsclean, aoflagger worked. but getting the following errors while trying to run 3 packages:

> lwimager 
lwimager: error while loading shared libraries: **libcasa_msvis.so**: cannot open shared object file: No such file or directory
> awimager
awimager: error while loading shared libraries: **libcasa_msvis.so**: cannot open shared object file: No such file or directory
> meqserver 
meqserver: error while loading shared libraries: **libcasa_msvis.so**: cannot open shared object file: No such file or directory

Because of this meqserver problem, cannot start a server in meqbrowser.

**Comment by gijzelaerr** [comment]
I experience no problems running lwimager on kern-1. Can you give me the
output of the command `$ dpkg -l meqtrees casarest lofar libcasa-casa2`.

for me that is:
```
$ dpkg -l meqtrees casarest lofar libcasa-casa2
Desired=Unknown/Install/Remove/Purge/Hold
|
Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  casarest                1.4.1-1kern3     amd64            standalone
radio interferometric imager derived from
ii  libcasa-casa2:amd64     2.1.0-1kern2     amd64            CASA core
modules
ii  lofar                   2.17.4-1         amd64            offline LOFAR
user software
ii  meqtrees                1.4.0-1kern1     amd64            MeqTrees meta
package that depends on all MeqTrees s
```

**Comment by kmbasad** [comment]
Many thanks for clarifying the problem. After dpkg-ing those four packages, I removed libcasa-casa2 completely, and then re-installed meqtrees. Now everything is working.
