### ISSUE TITLE
tempo2 inviroment variable doesn't work

### ISSUE THREAD

**Issue by abubakryagob** [kernsuite/packaging#38]
I'm trying to run tempo2 from outside docker but it didn't work.
Environment variable >TEMPO2< not set
and
I can't find tempo2 observatories.dat and "running directory"
PSRCAT: Unable to open catalogue file: /pulsar/psr/runtime/psrcat/psrcat.db

Regards,

**Comment by gijzelaerr** [comment]
did you try `TEMPO2=/usr` ?

**Comment by gijzelaerr** [comment]
for psrcat, the file is located in `/usr/share/psrcat/psrcat.db`. Do you know how to set it?

**Comment by abubakryagob** [comment]
It didn't work TEMPO2=/usr
for the psrcat, I don't  know how to set it

**Comment by gijzelaerr** [comment]
what is the command you are trying to run?

**Comment by gijzelaerr** [comment]
if you are not replying to my messages i can't help you.

**Comment by gijzelaerr** [comment]
no reply from end user, closing issue. Please re-open if you suddenly feel the urge to reply
