### ISSUE TITLE
Update wsclean to 2.3

### ISSUE THREAD

**Issue by ajstewart** [kernsuite/packaging#40]
Could wsclean on kern-dev be updated to 2.3 please?

**Comment by gijzelaerr** [comment]
ok unfortunately the auto update to 2.3 doesn't work since the Debian patches don't apply cleanly to 2.3. I'll see if we can get it updated in Debian first and then backport it to kern-dev

https://tracker.debian.org/pkg/wsclean

**Comment by gijzelaerr** [comment]
actually, it was easier than I thought. Packaged and uploaded to the dev PPA:

https://launchpad.net/~kernsuite/+archive/ubuntu/kern-dev/+build/12370202

**Comment by ajstewart** [comment]
Thanks!
