### ISSUE TITLE
'~kernsuite' user or team does not exist.

### ISSUE THREAD

**Issue by Nthabi83** [kernsuite/packaging#41]
I am trying to install casacore on ubuntu 16.04 and for the past week and everytime I add the repository  i keep getting the error: 
Cannot add PPA: 'ppa:~kernsuite/ubuntu/kern-2'.
ERROR: '~kernsuite' user or team does not exist.
Is it possible that your servers have been down recently or maybe I am doing something wrong?.

**Comment by gijzelaerr** [comment]
What is the command you are using to add the repository and where did you find that command?

**Comment by gijzelaerr** [comment]
no reply from end user, closing issue. Please re-open if you suddenly feel the urge to reply
