### ISSUE TITLE
aoflagger/lofar NDPPP shared library missing

### ISSUE THREAD

**Issue by mknapp55** [kernsuite/packaging#42]
NDPPP is complaining about a missing shared library for aoflagger (libdppp.aoflag.so).  I've uninstalled and reinstalled both lofar and aoflagger to no avail.

Example error:

`terminate called after throwing an instance of 'casa::AipsError'
  what():  Shared library aoflag not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
libdppp_aoflag.so: cannot open shared object file: No such file or directory`

**Comment by gijzelaerr** [comment]
this is a bug in the LOFAR package. please try to install the lofar-dev package and let me know if that solves the problem.

**Comment by mknapp55** [comment]
Yes, the lofar-dev package did fix the problem.  Thanks,

**Comment by gijzelaerr** [comment]
ok so @tammojan another confirmation that NDPPP is linking to the wrong SO file.

**Comment by tammojan** [comment]
How do I recreate this issue? An ubuntu 16.04 docker with kern-2 and which packages?

**Comment by gijzelaerr** [comment]
```
FROM kernsuite/base:2
RUN docker-apt-install lofar
CMD NDPPP
```
