### ISSUE TITLE
Can't see blockio.h while pip install python-casacore in virtualenv

### ISSUE THREAD

**Issue by landmanbester** [kernsuite/packaging#44]
pip falls over while installing python-casacore in virtualenv. Here is my output

pip install python-casacore
Collecting python-casacore
  Using cached python-casacore-2.1.2.tar.gz
Requirement already satisfied: numpy in ./lib/python2.7/site-packages (from python-casacore)
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages (from python-casacore)
Requirement already satisfied: appdirs>=1.4.0 in ./lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: packaging>=16.8 in ./lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: six>=1.6.0 in ./lib/python2.7/site-packages (from setuptools->python-casacore)
Requirement already satisfied: pyparsing in ./lib/python2.7/site-packages (from packaging>=16.8->setuptools->python-casacore)
Building wheels for collected packages: python-casacore
  Running setup.py bdist_wheel for python-casacore ... error
  Complete output from command /home/landman/virtualenvs/mb/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Uu5gao/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpu9v3Kipip-wheel- --python-tag cp27:
  Warning: could not find casa library dir for dependency tracking.
  Possibly not rebuilding. Specify --force to force a rebuild.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/images.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/quanta.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/functionals.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/tables.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/measures.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/fitting.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/__init__.py -> build/lib.linux-x86_64-2.7/pyrap
  copying pyrap/util.py -> build/lib.linux-x86_64-2.7/pyrap
  creating build/lib.linux-x86_64-2.7/casacore
  copying casacore/six.py -> build/lib.linux-x86_64-2.7/casacore
  copying casacore/__init__.py -> build/lib.linux-x86_64-2.7/casacore
  creating build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/image.py -> build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/__init__.py -> build/lib.linux-x86_64-2.7/pyrap/images
  copying pyrap/images/coordinates.py -> build/lib.linux-x86_64-2.7/pyrap/images
  creating build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablerow.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableiter.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/table.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/wxtablebrowser.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableindex.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablecolumn.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tablehelper.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/msutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/tableutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
  copying casacore/tables/__init__.py -> build/lib.linux-x86_64-2.7/casacore/tables
  creating build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/image.py -> build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/__init__.py -> build/lib.linux-x86_64-2.7/casacore/images
  copying casacore/images/coordinates.py -> build/lib.linux-x86_64-2.7/casacore/images
  creating build/lib.linux-x86_64-2.7/casacore/functionals
  copying casacore/functionals/functional.py -> build/lib.linux-x86_64-2.7/casacore/functionals
  copying casacore/functionals/__init__.py -> build/lib.linux-x86_64-2.7/casacore/functionals
  creating build/lib.linux-x86_64-2.7/casacore/util
  copying casacore/util/substitute.py -> build/lib.linux-x86_64-2.7/casacore/util
  copying casacore/util/__init__.py -> build/lib.linux-x86_64-2.7/casacore/util
  creating build/lib.linux-x86_64-2.7/casacore/fitting
  copying casacore/fitting/fitting.py -> build/lib.linux-x86_64-2.7/casacore/fitting
  copying casacore/fitting/__init__.py -> build/lib.linux-x86_64-2.7/casacore/fitting
  creating build/lib.linux-x86_64-2.7/casacore/measures
  copying casacore/measures/__init__.py -> build/lib.linux-x86_64-2.7/casacore/measures
  creating build/lib.linux-x86_64-2.7/casacore/quanta
  copying casacore/quanta/quantity.py -> build/lib.linux-x86_64-2.7/casacore/quanta
  copying casacore/quanta/__init__.py -> build/lib.linux-x86_64-2.7/casacore/quanta
  running build_ext
  building 'casacore.fitting._fitting' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fitting.cc -o build/temp.linux-x86_64-2.7/src/fitting.o
  c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/fit.o build/temp.linux-x86_64-2.7/src/fitting.o -lcasa_scimath -lcasa_scimath_f -lboost_python-py27 -lcasa_python -o build/lib.linux-x86_64-2.7/casacore/fitting/_fitting.so
  building 'casacore.functionals._functionals' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/functional.cc -o build/temp.linux-x86_64-2.7/src/functional.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/functionals.cc -o build/temp.linux-x86_64-2.7/src/functionals.o
  c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/functional.o build/temp.linux-x86_64-2.7/src/functionals.o -lcasa_scimath -lcasa_scimath_f -lboost_python-py27 -lcasa_python -o build/lib.linux-x86_64-2.7/casacore/functionals/_functionals.so
  building 'casacore.images._images' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/images.cc -o build/temp.linux-x86_64-2.7/src/images.o
  In file included from /usr/include/casacore/fits/FITS/hdu.h:33:0,
                   from /usr/include/casacore/images/Images/FITS2Image.tcc:38,
                   from /usr/include/casacore/images/Images/FITSImage.h:329,
                   from src/images.cc:36:
  /usr/include/casacore/fits/FITS/blockio.h:35:50: fatal error: fitsio.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-casacore
  Running setup.py clean for python-casacore
Failed to build python-casacore
Installing collected packages: python-casacore
  Running setup.py install for python-casacore ... error
    Complete output from command /home/landman/virtualenvs/mb/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Uu5gao/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8llxhb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/landman/virtualenvs/mb/include/site/python2.7/python-casacore:
    Warning: could not find casa library dir for dependency tracking.
    Possibly not rebuilding. Specify --force to force a rebuild.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/images.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/quanta.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/functionals.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/tables.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/measures.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/fitting.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/__init__.py -> build/lib.linux-x86_64-2.7/pyrap
    copying pyrap/util.py -> build/lib.linux-x86_64-2.7/pyrap
    creating build/lib.linux-x86_64-2.7/casacore
    copying casacore/six.py -> build/lib.linux-x86_64-2.7/casacore
    copying casacore/__init__.py -> build/lib.linux-x86_64-2.7/casacore
    creating build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/image.py -> build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/__init__.py -> build/lib.linux-x86_64-2.7/pyrap/images
    copying pyrap/images/coordinates.py -> build/lib.linux-x86_64-2.7/pyrap/images
    creating build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablerow.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableiter.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/table.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/wxtablebrowser.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableindex.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablecolumn.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tablehelper.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/msutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/tableutil.py -> build/lib.linux-x86_64-2.7/casacore/tables
    copying casacore/tables/__init__.py -> build/lib.linux-x86_64-2.7/casacore/tables
    creating build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/image.py -> build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/__init__.py -> build/lib.linux-x86_64-2.7/casacore/images
    copying casacore/images/coordinates.py -> build/lib.linux-x86_64-2.7/casacore/images
    creating build/lib.linux-x86_64-2.7/casacore/functionals
    copying casacore/functionals/functional.py -> build/lib.linux-x86_64-2.7/casacore/functionals
    copying casacore/functionals/__init__.py -> build/lib.linux-x86_64-2.7/casacore/functionals
    creating build/lib.linux-x86_64-2.7/casacore/util
    copying casacore/util/substitute.py -> build/lib.linux-x86_64-2.7/casacore/util
    copying casacore/util/__init__.py -> build/lib.linux-x86_64-2.7/casacore/util
    creating build/lib.linux-x86_64-2.7/casacore/fitting
    copying casacore/fitting/fitting.py -> build/lib.linux-x86_64-2.7/casacore/fitting
    copying casacore/fitting/__init__.py -> build/lib.linux-x86_64-2.7/casacore/fitting
    creating build/lib.linux-x86_64-2.7/casacore/measures
    copying casacore/measures/__init__.py -> build/lib.linux-x86_64-2.7/casacore/measures
    creating build/lib.linux-x86_64-2.7/casacore/quanta
    copying casacore/quanta/quantity.py -> build/lib.linux-x86_64-2.7/casacore/quanta
    copying casacore/quanta/__init__.py -> build/lib.linux-x86_64-2.7/casacore/quanta
    running build_ext
    building 'casacore.fitting._fitting' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fit.cc -o build/temp.linux-x86_64-2.7/src/fit.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/fitting.cc -o build/temp.linux-x86_64-2.7/src/fitting.o
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/fit.o build/temp.linux-x86_64-2.7/src/fitting.o -lcasa_scimath -lcasa_scimath_f -lboost_python-py27 -lcasa_python -o build/lib.linux-x86_64-2.7/casacore/fitting/_fitting.so
    building 'casacore.functionals._functionals' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/functional.cc -o build/temp.linux-x86_64-2.7/src/functional.o
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/functionals.cc -o build/temp.linux-x86_64-2.7/src/functionals.o
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/functional.o build/temp.linux-x86_64-2.7/src/functionals.o -lcasa_scimath -lcasa_scimath_f -lboost_python-py27 -lcasa_python -o build/lib.linux-x86_64-2.7/casacore/functionals/_functionals.so
    building 'casacore.images._images' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/images.cc -o build/temp.linux-x86_64-2.7/src/images.o
    In file included from /usr/include/casacore/fits/FITS/hdu.h:33:0,
                     from /usr/include/casacore/images/Images/FITS2Image.tcc:38,
                     from /usr/include/casacore/images/Images/FITSImage.h:329,
                     from src/images.cc:36:
    /usr/include/casacore/fits/FITS/blockio.h:35:50: fatal error: fitsio.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/landman/virtualenvs/mb/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Uu5gao/python-casacore/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8llxhb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/landman/virtualenvs/mb/include/site/python2.7/python-casacore" failed with error code 1 in /tmp/pip-build-Uu5gao/python-casacore/

I have all of casacore-{data,dev,tools} installed as well as wcslib-{dev,tools} and have checked that the file /usr/include/casacore/fits/FITS/blockio.h exists. This doesn't happen when I pip install python-casacore outside virtualenv. What am I missing?

**Comment by gijzelaerr** [comment]
you are missing `fitsio.h` which is part of `libcfitsio3-dev`. If you can't read the readme i think you should just use the packages ;)
