### ISSUE TITLE
kvis complains of no base directory

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#47]
```
oms@jake:~$ kvis
Environment variable KARMABASE not found
Error statting "/usr/local/karma" (compiled in)	No such file or directory
Error statting "/usr/local/karma" (default)	No such file or directory
No Karma base directory found!
Port allocated: 12115
```
I'm not sure if this is just an ignorable warning, or if functionality is affected. @twillis449, could you check please?

**Comment by twillis449** [comment]
Hum - it looks like on my computer at work, it can be ignored. It doesn't matter whether KARMABASE is defined or not. The image pops up.  However I will check on another laptop I have at home. That's where the errors I saw this morning were appearing.

**Comment by twillis449** [comment]
Murphys  Law I guess ...

This morning I was getting a bunch of weird messages (see at end below) like
canvas_dressing_get_size: error sizing string: "aAbBgGpP!" 
and the images looked very odd

but now with or without KARMABASE defined things seem to working. :) 
and the 'canvas_dressing' stuff is not appearing.

[jake 9:03pm] [pol_sims]> kvis 
askap_uniform_lwimager_beam5_7x7_grid_raw_3_IQUV_151.fits

Error statting "/usr/local/karma" (from KARMABASE)    No such file or 
directory
Error statting "/usr/local/karma" (compiled in)    No such file or directory
Error statting "/usr/local/karma" (default)    No such file or directory
No Karma base directory found!
Running m_alloc and m_free without checking
Port allocated: 14540
Warning: Cannot allocate colormap entry for "black"
_kwin_X11_get_colour: error allocating colour: "green" in visualID: 0x22
_kwin_X11_get_colour: error allocating colour: "white" in visualID: 0x22
Unknown unit: "deg" for: "CUNIT1", dropping
Unknown unit: "deg" for: "CUNIT2", dropping
Unknown unit: " " for: "CUNIT3", dropping
Non-standard "CUNIT4" has no effect: dropping
Computed scaled min: -0.151493  max: 0.997831
Computed unscaled min: -0.151493  max: 0.997831
__kwin_hershey_initialise: error opening font file: "/share/fonts.dat"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"

**Comment by gijzelaerr** [comment]
To get rid of the error run `$ KARMABASE=/usr kvis`.

I tried to obtain the karma source and compile it with this variable hard coded, but the author didn't reply to my emails.

**Comment by o-smirnov** [comment]
The joys of abandonware.

I wonder, couldn't we ship the binary as ``/usr/bin/kvis.bin``, and make ``/usr/bin/kvis`` a wrapper script that sets KARMABASE? Or would that break more than it would fix?

**Comment by twillis449** [comment]
Easier just to set things up in one'd .bashrc or .cshrc file. I mostly  still use tcsh for my shell so after I put

setenv KARMABASE /usr
setenv KARMABINPATH /usr/bin
setenv KARMALIBPATH /usr/lib
setenv KARMAROOT /usr

in my .cshrc file, all the complaints go away.

But for a lot of users - like Oleg says a wrapper script may be the way to go.

**Comment by twillis449** [comment]
@gijzelaerr  - Its veryUNlikely you will hear back from the author, Richard Gooch. Here is his LinkedIn profile - https://www.linkedin.com/in/richard-gooch-00412bb1  I find it hilarious that he claims to be a 'team leader'  Back when I knew him a less likely individual you would want on a 'team' I can't imagine. I actually may have some source code for an earlier version of kvis floating around - I'll look. Gooch never released the final version of the source code despite being Russ Taylor's employee at the University of Calgary.

**Comment by gijzelaerr** [comment]
easiest back thing would be to just to install in /usr/local, but modern package management doesn't allow us.

I mailed him, he doesnt reply. I'm done playing investigator. if somebody wants to try again, be my guest.

**Comment by twillis449** [comment]
@gijzelaerr  Sorry - I've edited my comment above to say 'UNlikely' !!! And that's what I meant in the first place - LOL  What ticks me off is  the the University of Calgary should be the intellectual property holder of the kvis source code but they let Gooch skip out of  town without getting the source code from him. 

By the way - I did find my source code for an earlier release of the KARMA package. Back then kvis was called 'kview'.  I did try compiling the code yesterday but got a few bazillion errors as I think this stuff was last compiled ca 2000 with something like gcc 2.95 or thereabouts.  This visualizer even had a glish eventloop handler.  For your amusement I'm attaching the file here.

[karma_acsis.tar.gz](https://github.com/kernsuite/packaging/files/1042525/karma_acsis.tar.gz)

And indeed looking through the code you will need to get @o-smirnov  to dig up his last compiled version of aips++ as it needs some glish libraries in order to link. (I believe I also have a 'last version' of aips++. I will check.)

**Comment by gijzelaerr** [comment]
there are some sources available on the FTP

ftp://ftp.atnf.csiro.au/pub/software/karma/archive/

but the time stamp is 6 days after 9/11.

**Comment by twillis449** [comment]
Actually, the interesting file there is karma-1.7.20-common.tar.bz2 with a timestamp of 2011-07-27. It contains instructions for building kvis from scratch. Unfortunately ... this build is still designed for use with a glish interface interface. So you would have to get rid of the glish interface code for a build to link. And  it also needs a complete build of support karma libraries with e.g. karma.src-v1.7.tar.gz, for which there are no build instructions.
