### ISSUE TITLE
T2runtime missing?

### ISSUE THREAD

**Issue by bretonr** [kernsuite/packaging#48]
After installing tempo2 (`sudo apt-get install tempo2`), the environment variable `$TEMPO2` does not get set automatically, which I guess is fair enough. It is supposed to point to the `T2runtime` directory, which I could not locate as being install somewhere when install the package. I have just missed it? As a quick fix, I have downloaded the tempo2 source code from its github repo as it contains the `T2runtime` folder, and then pointed the environment variable to it. Perhaps this needs fixing? Or maybe it is just that it's at an location unknown from me?

I wondering if it might not be good having a some page when a list of environment variables which one should set after install specific packages be made?

**Comment by gijzelaerr** [comment]
2 issues here. I probably forgot to add the installation of the T2runtime folder.

About the environment variable, best is to patch the source code and hardcode the TEMPO2 variable and set it to `/usr`. Feel free to supply such a patch :)

**Comment by gijzelaerr** [comment]
I updated the tempo2 pacakage to 2017.03.1 in KERN-dev, which will become KERN-3. The installation now also includes the t2runtime folder. The content is copied to `/usr/share/tempo2`. You still need to set the environment variable though, I couldn't figure out how to modify the source so it looks in `/usr/share/tempo2`. If you know how to please let me know :)
