### ISSUE TITLE
libtempo2pred.so.0 missing

### ISSUE THREAD

**Issue by bretonr** [kernsuite/packaging#49]
I have installed _tempo2_ (`sudo apt-get install tempo2`) and after fixing the (possible) issue with the missing `T2runtime` directory ( #48 ) it works fine.

I have then installed the _psrchive_ suite (`sudo apt-get install psrchive`). When attempting to run one of its programmes (`pav -h`) it crashes with the following error: `pav: error while loading shared libraries: libtempo2pred.so.0: cannot open shared object file: No such file or directory`.

It appears that the _tempo2_ libraries are missing. The environment variable `$LD_LIBRARY_PATH` is not set and this possibly needs to be done. However I could not locate the missing library anywhere.

Any clue?

**Comment by gijzelaerr** [comment]
I Will have a look in October/November when I'm employed by SKA (again).

**Comment by bretonr** [comment]
No problem! I've been meaning to send some patches but got really tied up
with multiple other things. If I find time I'll give it a shot.

**Comment by gijzelaerr** [comment]
I think tis is a problem with psrchive, tempo2 actually contains the library but with a different SO number:

```
$ dpkg -S libtempo2pred.so
tempo2: /usr/lib/x86_64-linux-gnu/libtempo2pred.so.1.0.1
tempo2: /usr/lib/x86_64-linux-gnu/libtempo2pred.so.1
```

**Comment by gijzelaerr** [comment]
correction, I think it is a problem with the package of psrchive, which is linked to an older version. Since it is quite broken anyway, i'll update it to a never version which will trigger a recompile.

uploading `2012.12+20170930-1` to KERN-dev and KERN-2 as we speak.
