### ISSUE TITLE
Tigger 1.3.4 fails to load fits files

### ISSUE THREAD

**Issue by ArunAniyan** [kernsuite/packaging#5]
Tigger 1.3.4 gives me this error whenever I try to load a fits file (which other image viewers load normally)  

Error loading FITS image 1466813419_1284.hh_vv.ms_1-7_fixed.ms_I_3deg_pself1.image.fits: 'Header' object has no attribute 'ascard'. This may be due to a bug in Tigger; if the FITS file loads fine in another viewer, please send the FITS file, along with a copy of any error messages from the text console, to osmirnov@gmail.com.

The traceback on the terminal shows this 

File "/usr/lib/python2.7/dist-packages/Tigger/Images/Manager.py", line 128, in loadImage
    image = SkyImage.FITSImagePlotItem(str(filename));
  File "/usr/lib/python2.7/dist-packages/Tigger/Images/SkyImage.py", line 553, in **init**
    self.read(filename,hdu);
  File "/usr/lib/python2.7/dist-packages/Tigger/Images/SkyImage.py", line 581, in read
    hdr1 = pyfits.Header(filter(lambda x:not str(x).startswith('HISTORY'),hdr.ascard));
AttributeError: 'Header' object has no attribute 'ascard'

I have not seen this issue on the same version of tigger on ubuntu 14.04

**Comment by gijzelaerr** [comment]
I think this is an issue with tigger itself?

**Comment by gijzelaerr** [comment]
please report tigger issues here https://github.com/ska-sa/tigger
