### ISSUE TITLE
casacore build flags (ENABLE_TABLELOCKING)

### ISSUE THREAD

**Issue by mknapp55** [kernsuite/packaging#50]
I ran into an issue with casacore that I suspect is related to the Lustre filesystem on the cluster I'm using (see https://www.astron.nl/lofarwiki/doku.php?id=public:install_lofar_centos6.5, 3.2 casacore for why I suspect Lustre).  The error I get when running NDPPP is:
```
terminate called after throwing an instance of 'casa::TableError'
  what():  Error (Function not implemented) when acquiring lock on /data/working_L531971/pipeline/L531971_SB470_uv.calibrator-flagcal/table.lock
```
Based on the information in the link above, casacore table locking doesn't play nice with Lustre.  My question is whether there's any way to turn off table locking when installing casacore via Kern (or after installing).  I am very hesitant to try installing from source and invoking that build option because I don't want to mess up everything that depends on casacore.  Is doing a build from source the only option?  Is there any way that build options like `-DENABLE_TABLELOCKING=NO` can be accessed when installing a Kern module via apt-get?

FWIW, I'm running casacore/NDPPP/genericpipeline/etc. from a Singularity container I built and maintain myself.  It has worked on other single node machines, but threw the error above when I tried running it on data stored on a Lustre filesystem.

**Comment by gijzelaerr** [comment]
interesting. I think best to report this problem upstream and check if we can backport the fix to the casacore in this release. Can you report the issue upstream and ask if the solution can be backported to 2.2.x? That is the only way it can be solved in KERN ATM, we dont want do disable tablelocking on the repo since maybe somebody is depending on it.

**Comment by gijzelaerr** [comment]
@mknapp55 has there been any development on this issue? Is there something I can do?

Not sure if it is a good idea to enable this by default?

**Comment by gijzelaerr** [comment]
closing this issue since @mknapp55 seems to not care anymore.
