### ISSUE TITLE
WSClean 2.4

### ISSUE THREAD

**Issue by mknapp55** [kernsuite/packaging#52]
Could you build wsclean 2.4?  Factor doesn't work without it, but the current wsclean package is 2.3.

**Comment by gijzelaerr** [comment]
I will update all packages in the KERN-3 release, which is scheduled in October / November.

**Comment by mknapp55** [comment]
Ok.  FWIW, current versions of both factor and PiLL (HBA and LBA pipelines for LOFAR) now require WSClean 2.4.  I installed from source so I could use them.

**Comment by gijzelaerr** [comment]
WSclean 2.4 has been uploaded to KERN-dev.

Additionally, factor 1.3 and prefactor 2.0.2 has been uploaded to KERN-dev also.
