### ISSUE TITLE
Misnamed MeqTrees packages?

### ISSUE THREAD

**Issue by IanHeywood** [kernsuite/packaging#54]
Several of the MeqTrees-related packages seem to be misnamed in the "Package" column on the kern-2 website, e.g. pyxis, owlcat, purr, meqtrees-cattery etc.

```
$ sudo apt install pyxis
...
E: Unable to locate package pyxis
```

All the ones I've had problems with can be fixed by just adding a "python-" prefix:

```
$ sudo apt install python-pyxis
```

**Comment by gijzelaerr** [comment]
I'm not sure what 'package' column your referring to. If it is the launchpad page, those are the names of the source package. A source package can result in multiple binary packages. technically a python library debian package should have the python- prefix. When a python package  is bundled with an executable script it could also have a meta package with the short name which depends on the python library. I neglected to do that in some cases.  But it is not really unexpected, it could be a bit more convenient.

**Comment by IanHeywood** [comment]
> I'm not sure what 'package' column your referring to.

The 'Package' column [here](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-2).

I was following the instructions which say:

```
$ sudo apt-get install [package]
```

Obviously not critical, but not consistent either.

**Comment by gijzelaerr** [comment]
I added a pyxis meta package.

**Comment by gijzelaerr** [comment]
added metapackage for owlcat also.

There is already a 'meqtrees' meta package that installs everything.
