### ISSUE TITLE
add cubical

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#56]
https://github.com/ratt-ru/CubiCal/releases/tag/v0.9.1

**Comment by gijzelaerr** [comment]
first this issue needs to be resolved:

http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules

**Comment by gijzelaerr** [comment]
@JSKenyon what is the status of this?

**Comment by JSKenyon** [comment]
@gijzelaerr I sort of gave up on this one, if I am completely honest. I ended up butchering my setup script to the point that it stopped working as intended. I will take a look at my branch again and clean it up. Maybe we can figure out what else should be done from there.

**Comment by JSKenyon** [comment]
@gijzelaerr [Here](https://github.com/ratt-ru/CubiCal/blob/rev-setup/setup.py) is a different version of setup.py. That branch bundles the .c and .cpp code, and only uses Cython if it is available. I based this off of the [rasterio](https://github.com/mapbox/rasterio) repository. They have the same numpy dependency.

**Comment by gijzelaerr** [comment]
done! 0.9.2.1 is in KERN-dev and KERN-3
