### ISSUE TITLE
Kern 2 casacore-dev missing dependencies

### ISSUE THREAD

**Issue by bennahugo** [kernsuite/packaging#59]
Ubuntu 16.04 casacore-dev is missing the following dev dependencies needed when installing python-casacore using pip into a venv (currently no linux wheel is available through PyPI).
wcslib-dev
libcfitsio-dev

**Comment by gijzelaerr** [comment]
You should install those dependencies manually, installing  casacore-dev doesn't mean you want to pip python-casacore.

You can install the dependencies for python-casacore using the dependencies fiend from the source package:
`$ sudo apt-get build-dep python-casacore`
