### ISSUE TITLE
Tigger 1.3.4 fails when creating a sky model in kern-dev but not in radio-astro

### ISSUE THREAD

**Issue by sjperkins** [kernsuite/packaging#6]
On kernsuite/kern-dev, tigger-convert (and tigger) fall over on this [sky_model.txt](https://github.com/kernsuite/packaging/files/370999/sky_model.txt). The tigger version is 1.3.4.

``` bash
$ tigger-convert -f sky_model.txt sky_model.lsm.html
Reading sky_model.txt (ASCII table)
Error loading model: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
```

However the exact same sky model succeeds on radio-astro/main version of tigger 1.3.4.

Could this be a python 3 issue?

**Comment by gijzelaerr** [comment]
This is an issue with tigger. please report tigger issues here https://github.com/ska-sa/tigger
