### ISSUE TITLE
casa has been packaged up for anaconda

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#65]
maybe we can learn from that!

https://github.com/conda-forge/casacore-feedstock/pull/11

**Comment by gijzelaerr** [comment]
Tried to learn from it, but it didn't help. basically they bundle their own casacore version (also). We can't that. So unless casa is going to synchronise their development with the casacore releases properly casa is impossible to package.

**Comment by tammojan** [comment]
If it helps, we can make casacore releases for the version that CASA uses in a particular release (they use a git submodule for casacore, so it's easy to track which commit of casacore is bundled in CASA).

**Comment by gijzelaerr** [comment]
No, not really. casacore 2.4.1 is in Ubuntu and Debian and that is the version we have to use. but your comment is still useful. Which version of CASA is depending on something that is the closest to an unmodified casacore 2.4.1?
