### ISSUE TITLE
Packaging MeerKATHI (MeerKAT pipeline)

### ISSUE THREAD

**Issue by SpheMakh** [kernsuite/packaging#68]
We would like to package this in the coming weeks. Its private for now, but @gijzelaerr has access

https://github.com/ska-sa/meerkathi

**Comment by gijzelaerr** [comment]
ok well then I wait until it becomes public.

**Comment by gijzelaerr** [comment]
@SpheMakh this code is still not public, so i can't make a release.

**Comment by gijzelaerr** [comment]
This is probably going to be replaced (or augmented) by https://github.com/ska-sa/den

i'm not sure if it makes sense to package up pipelines, since they often need to be modified. until now what we do is package up the dependencies, but the pipeline itself is also checked out as entry point.

**Comment by gijzelaerr** [comment]
Sphe might need this in the future, for now we just wait.

**Comment by gijzelaerr** [comment]
one year later and still closed source, going to close this issue.
