### ISSUE TITLE
PRESTO dependencies

### ISSUE THREAD

**Issue by loostrum** [kernsuite/packaging#7]
PRESTO uses TEMPO for many routines. Maybe add this as a dependency?
It also include some python2 routines. The most used ones require at least numpy, scipy & matplotlib. Also make sure that python can find the routines, they're in /usr/lib/python now.

**Comment by gijzelaerr** [comment]
@loostrum just to check, that is tempo and not tempo2? Does presto work correctly if you install the tempo package manually?

**Comment by loostrum** [comment]
Hi @gijzelaerr, 
This is indeed not tempo2 but tempo. After installing tempo manually (using git, will check again using `docker-apt-install tempo` when #8 is fixed), PRESTO works fine.

**Comment by gijzelaerr** [comment]
I added the dependencies. Also, I think I install all python files now in the python-presto package. Can you verify?

**Comment by loostrum** [comment]
OK, tempo is indeed installed now and presto can find the binary. The python-presto package works too. Python still needs numpy,scipy,matplotlib,astropy for the routines to work.

**Comment by gijzelaerr** [comment]
the python-presto package depends on numpy, scipy and matplotlib right?

this is the first time you mention astropy?

**Comment by loostrum** [comment]
Somehow it doesn't, they don't get installed:
`The following NEW packages will be installed:`
`python-presto`
No mention of other python packages there.
I missed astropy before, it's only used in a few scripts. It would be useful to have though.

**Comment by gijzelaerr** [comment]
you are right, somehow dependencies where missing... i added them, included astropy. package is uploaded, will soon be available.

**Comment by loostrum** [comment]
It now installs the dependencies correctly. We're almost there I think. One last thing has to do with te way the scripts currently import presto routines. They use e.g.
`import infodata` 
instead of 
`from presto import infodata`
So python _can_ find presto but the scripts want to import the routines directly.

**Comment by gijzelaerr** [comment]
jah, that sucks a bit. Until presto people solve this properly you could try setting your `PYTHONPATH` to `/usr/lib/python2.7/dist-packages/presto`

**Comment by loostrum** [comment]
I'll do that. Then everything seems to work fine now.
