### ISSUE TITLE
CubiCal installs but doesn't run in docker

### ISSUE THREAD

**Issue by JSKenyon** [kernsuite/packaging#72]
I made an image with the following in my dockerfile: 
```
FROM kernsuite/base:3
RUN docker-apt-install cubical
```
If I then do:
```
docker run -i -t cubidock
```
Running:
```
gocubical
```
I get:
```
Traceback (most recent call last):
  File "/usr/bin/gocubical", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
Is this a problem with the packaging process, or an odd interaction with setuptools entrypoints?

**Comment by JSKenyon** [comment]
[This](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources) might be relevant.

**Comment by gijzelaerr** [comment]
what happens if you install the `python-pkg-resources` package?

**Comment by gijzelaerr** [comment]
seems to solve the problem. Somehow `python-pkg-resources` is not picked up automatically as an dependency. Will do when I update the package, for now you can work around the issue by installing the `python-pkg-resources` package manually.

**Comment by JSKenyon** [comment]
Thanks - yeah. Verified that it works for me too.
