### ISSUE TITLE
pymoresane package is empty

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#74]
Not much to go on here:
```
$ dpkg -L pymoresane
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/pymoresane
/usr/share/doc/pymoresane/copyright
/usr/share/doc/pymoresane/changelog.Debian.gz
$
```

**Comment by gijzelaerr** [comment]
should be fixed. Note there are 2 packages now, `python-pymoresane` for the library and `pymoresane` for the callable script.

**Comment by o-smirnov** [comment]
``pymoresane`` needs ``python-pymoresane`` to function, but the latter is not listed as a dependency of the former, so it doesn't auto-install.

**Comment by gijzelaerr** [comment]
it does? https://github.com/kernsuite-debian/pymoresane/blob/master/debian/control#L21
