### ISSUE TITLE
TEMPO needs some files that are missing

### ISSUE THREAD

**Issue by loostrum** [kernsuite/packaging#8]
TEMPO needs some configuration files and directories: tempo.hlp, tempo.cfg and the dirs referenced in the cfg file. These need to be located in the $TEMPO directory.

**Comment by gijzelaerr** [comment]
Hi @loostrum, thanks for reporting this.

What do you mean with "These need to be located in the $TEMPO directory". Does the tempo binary look at the `$TEMPO` variable at runtime to find these files? Do you know if it is possible to set a preconfigured path during compilation where tempo will look for this file?

**Comment by loostrum** [comment]
Hi @gijzelaerr,
It indeed checks the `$TEMPO` variable at runtime. This is hardcoded in src/tparin.f:

`src/tparin.f:95:      call getenv ('TEMPO',path)`
`src/tparin.f-96-      lpth = index(path,' ')-1`
`src/tparin.f-97-      hlpfile = path(1:lpth)//'/tempo.hlp'`

As you can see, this loads the tempo.hlp file. The `path` fortran variable is used in src/tempo.f to get  the tempo.cfg file:

`src/tempo.f:188:   cfgpath=path(1:lpth)//'/tempo.cfg'`

I don't see any options to change these at compilation, but I might be missing it as I'm not familiar with `autoconf` and `automake` magic. ~~The only thing I see is that the path to tempo.cfg can be changed at runtime using `tempo -d  /path/to/tempo.cfg`~~
**edit**: unlike what the tempo help suggests, `tempo -d /some/path` sets the directory containing both tempo.cfg and tempo.hlp at runtime.

**Comment by gijzelaerr** [comment]
ok, I think we need to patch the source code then, which itself not a big problem. Do you know how to modify the code? I have close to zero experience with fortran but that is something that can change.

**Comment by loostrum** [comment]
I don't have any experience with fortran, so I can't help you there unfortunately.

**Comment by gijzelaerr** [comment]
uploaded a new version that installs the help file in /usr/share/tempo. modifed source code to look for help file there.

**Comment by loostrum** [comment]
It can now indeed find the help file. The config file (`tempo.cfg`) is still missing though. In that file, the following files/folders are referenced and needed as well:

`clock/`
`tzpar/`
`ephem/`
`obsys.dat`

The other files mentioned in the config file are present in one of the three directories.

**Comment by gijzelaerr** [comment]
these problems are solved and are included in kern-dev and kern-1
