### ISSUE TITLE
Karma cannot overlay axes and axis labels

### ISSUE THREAD

**Issue by gigjozsa** [kernsuite/packaging#80]
Trying to create an overlay of axis labels by clicking on 
Overlay -> Axis Labels
then clicking on "Enable" on the widget results in an error

__kwin_hershey_initialise: error opening font file: "/share/fonts.dat"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"

on the command line and no axis labels. @bennahugo had the same problem and solved it before.

**Comment by gijzelaerr** [comment]
yeah a solution is welcome.

**Comment by bennahugo** [comment]
Just checked I use karma from KERN 3 on the comm machines. That has the overlay labels so I'm closing this for now. Stevie is still using KERN 2

**Comment by bennahugo** [comment]
Works on the imaging container
```
kat@imaging-container:~$ kvis
Port allocated: 12140
Warning: Cannot allocate colormap entry for "black"
_kwin_X11_get_colour: error allocating colour: "green" in visualID: 0x21
_kwin_X11_get_colour: error allocating colour: "white" in visualID: 0x21
```
Upgraded to KERN 3 on stevie and it can't find some of the shared files
```
Environment variable KARMABASE not found
Error statting "/usr/local/karma" (compiled in) No such file or directory
Error statting "/usr/local/karma" (default)     No such file or directory
No Karma base directory found!
Port allocated: 13545
Warning: Cannot allocate colormap entry for "black"
_kwin_X11_get_colour: error allocating colour: "green" in visualID: 0x21
_kwin_X11_get_colour: error allocating colour: "white" in visualID: 0x21
__kwin_hershey_initialise: error opening font file: "/share/fonts.dat"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"

```

**Comment by gijzelaerr** [comment]
Looks like the source needs to be patched to `KARMABASE` points to `/usr` by default.

**Comment by bennahugo** [comment]
yea I think so

**Comment by gijzelaerr** [comment]
does setting `KARMABASE` to `/usr` solve the problem?

**Comment by bennahugo** [comment]
No still complains about not finding the fonts file:
```
__kwin_hershey_initialise: error opening font file: "/usr/share/fonts.dat"
canvas_dressing_get_size: error sizing string: "aAbBgGpP!"
```

**Comment by bennahugo** [comment]
@gigjozsa Deploy the imaging-container for now: https://github.com/ska-sa/katdocker in the mean time. It should give you miriad etc.

**Comment by gijzelaerr** [comment]
the fonts are in `/usr/share/karma/fonts.dat`

**Comment by bennahugo** [comment]
hmm no this thing comes bundled with miriad.... which sets
```
KARMAINCLUDEPATH=/usr/local/miriad/borrow/karma//include
KARMALIBPATH=/usr/local/miriad/borrow/karma//lib
KARMA_VERSION=1.7.25
KARMASTATICLIBPATH=/usr/local/miriad/borrow/karma//static-lib
KARMABINPATH=/usr/local/miriad/borrow/karma//bin
KARMABASE=/usr/local/miriad/borrow/karma/
```

**Comment by gijzelaerr** [comment]
ok well the proper way to fix this is to patch the sourcecode.

**Comment by gijzelaerr** [comment]
@bennahugo @gigjozsa any suggestions on how to solve this properly? Or is it not an issue anymore?

**Comment by gigjozsa** [comment]
It still is an issue but there are currently no resources to solve it.

**Comment by gijzelaerr** [comment]
karma is a mess. The source code for 1.7.25 seems to be unavailable so the KERN packages are build from the distributed binaries. These binaries have hardcoded paths in them. In my opinion, karma is FUBAR. Closing this issue since this is probably not going to change.
