### ISSUE TITLE
wsclean and libwsclean0 need to be in sync

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#84]
Seeing this on a node:
```
$ dpkg -la|grep wscl
ii  libwsclean0:amd64                    2.4-1kern3                                   amd64        Fast generic widefield interferometric imager (shared library)
ii  wsclean                              2.5-1kern1                                   amd64        Fast generic widefield interferometric imager
$
```
This shouldn't be possible. The two things need to upgrade in lockstep, otherwise all sorts of confusion and hair-tearing ensues.

**Comment by gijzelaerr** [comment]
i don't know who did that and how that is possible, but that dependency is automatic and quite strict.

https://github.com/kernsuite-debian/wsclean/blob/master/debian/control#L26

There is no stricter control over this. I'm quite sure Debian would upgrade libwsclean0 if you update wsclean. Are you sure the packaging is not in a state of limbo? if so, did you run `apt-get update` and/or `apt-get install -f`?

**Comment by o-smirnov** [comment]
I did it. I installed wsclean 2.4 first, then when 2.5 came out, I just did ``apt-get install wsclean`` to upgrade. And evidently it did not upgrade the library. Am I missing something about how apt works?

**Comment by gijzelaerr** [comment]
I found out what the problem is. Since the ABI didn't change (that is what those SO version are for) this executable should still work with the older library and the library is not implicitly upgraded.

Are you experiencing issues? Then there is an ABI change and we should report that upstream.

**Comment by olebole** [comment]
One could just put
```
Depends: libwsclean0 (= ${binary:Version})
```
into `debian/control`, as it is done with `wsclean-dev`.

**Comment by gijzelaerr** [comment]
Would that be accepted in Debian also?

**Comment by olebole** [comment]
Sure. But see the [discussion in sourceforge](https://sourceforge.net/p/wsclean/tickets/130/)

**Comment by gijzelaerr** [comment]
added `libwsclean0 (= ${binary:Version})` to wsclean binary, uploaded to kern-3 and kern-dev.

Thanks, @olebole for your wisdom.
