### ISSUE TITLE
Please package latest tirific release 2.3.9

### ISSUE THREAD

**Issue by gigjozsa** [kernsuite/packaging#85]
https://github.com/gigjozsa/tirific/releases/tag/2.3.9
Thanks

**Comment by Athanaseus** [comment]
Hi @gigjozsa please be aware that the package tags are inconsistent, sometimes the version number is prefixed with `v` and other releases are not. e.g https://github.com/gigjozsa/tirific/releases/tag/v2.3.8 has one.

**Comment by gigjozsa** [comment]
Correct. Gijs requested the name tag to be changed to a letterless format. Before 2.3.9, all releases had a v. Thanks!

**Comment by gijzelaerr** [comment]
@gigjozsa where do you expect to find this? In KERN-4? In principle, we only push bug fixes to released  KERN bundles. Do you want this pushed to KERN-4 as a bug fix?

**Comment by gigjozsa** [comment]
This is a bugfix, yes. So for any new release (with improvements) to be implemeted in KERN, one should wait for the next KERN version. Is this correct?

**Comment by gijzelaerr** [comment]
yes. Idea is that a KERN release offers users a stable set of tools that won't change in functionality.

**Comment by gigjozsa** [comment]
Understood. This is a bugfix, though.

**Comment by gijzelaerr** [comment]
packaged and uploaded to kern-3. currently building on the build farm:

https://launchpad.net/~kernsuite/+archive/ubuntu/kern-3/+build/14458820

thanks @Athanaseus for updating!
