### ISSUE TITLE
Please package meqtrees-cattery-1.5.2

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#86]
I thought this was automatic now? https://github.com/ska-sa/meqtrees-cattery/releases

**Comment by gijzelaerr** [comment]
the pip might be, but the KERN packaging is not.

is it not in pip? then travis is failing.

**Comment by o-smirnov** [comment]
@gijzelaerr, pretty please? The release is still not in pip or KERN. Travis is passing.

**Comment by gijzelaerr** [comment]
it is probably not working since you didn't update the version number in `setup.py`.

I'll have a look

**Comment by gijzelaerr** [comment]
There was another error, apparently twine is a bit more strict uploading things to pypi:

```
HTTPError: 400 Client Error: '"Oleg Smirnov" <osmirnov@gmail.com>' is an invalid value for Author-email. Error: Invalid email address. see https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/
```
https://github.com/ska-sa/meqtrees-cattery/commit/e9bf19f7c0b13852d0d378ce13ae3ef57e836a19

After resolving these issues version 1.5.3 is now successfully on pypi and in KERN-dev and KERN-3

https://pypi.python.org/pypi/meqtrees_cattery/1.5.3
https://launchpad.net/~kernsuite/+archive/ubuntu/kern-3/+build/14315532
https://launchpad.net/~kernsuite/+archive/ubuntu/kern-dev/+build/14315531
