### ISSUE TITLE
LOFAR: gsm.py missing?

### ISSUE THREAD

**Issue by ajstewart** [kernsuite/packaging#87]
I've just installed LOFAR from kern-3 but it seems like gsm.py is missing, is this intentional? As it is still available when I load the lofar tools on CEP3. It's usually located in /usr/bin/. Perhaps it's installed through a different package now?

**Comment by gijzelaerr** [comment]
I don't see a file named `gsm.py` in the original LOFAR `3.0.3` tarball so i guess this is not a packaging issue.

**Comment by ajstewart** [comment]
Hmm ok - thanks I'll ask the lofar people!

**Comment by gijzelaerr** [comment]
actually I'm wrong, there is a gsm.py file upstream:

https://svn.astron.nl/LOFAR/tags/LOFAR-Release-3_0_9/CEP/GSM/src/gsm.py

The GSM submodule got removed from the Debian package since it depends on MonetDB and the install scripts are broken. The LOFAR people said the GSM is not intended for 3rd party usage.

**Comment by ajstewart** [comment]
Right, that's a bit annoying as I still use it now and again. I guess I could just re-install it manually using the files from an old installation.

Thanks again!

**Comment by gijzelaerr** [comment]
maybe worthwhile to report it anyway upstream and point to this thread.

**Comment by ajstewart** [comment]
For future reference in case anyone stumbles across this, gsm.py can now be found here to install separately:

https://github.com/bartscheers/gsm

**Comment by SterVeen** [comment]
Also a:
pip install gsm 
will do the trick.

**Comment by gijzelaerr** [comment]
i'll upload a Debian package to KERN when i find the time, it is quite trivial.

**Comment by gijzelaerr** [comment]
GSM and pymonetdb have been uploaded to KERN-dev
