### ISSUE TITLE
psrcat does not load system-installed database file

### ISSUE THREAD

**Issue by griffinfoster** [kernsuite/packaging#92]
psrcat in KERN-3 (v1.57) does not load the psrcat.db file:

> psrcat 
PSRCAT: Unable to open catalogue file: /pulsar/psr/runtime/psrcat/psrcat.db

A local version of psrcat.db can be used with the -db_file option, but it would be nice to have a global version.

**Comment by gijzelaerr** [comment]
updated to psrcat 1.58, fixed default search path, uploaded to KERN-3 (xenial) and KERN-dev (bionic).
