### ISSUE TITLE
lofar python3 packages

### ISSUE THREAD

**Issue by jamiefarnes** [kernsuite/packaging#94]
I was just wondering if it was possible to make a feature request. I have been attempting to install a few specific packages, that I was wishing to use with python3. These include:
* lofar
* liblofar-pystationresponse0
* python-lofar
* rmextract
Currently it seems that these are only available in python2, although I can download and install all the packages individually for use in python3. Is there any chance it may please be possible to provide python3 support for these in an upcoming release?

Thanks so much.
All the best,
Jamie

**Comment by gijzelaerr** [comment]
I expect to have time to try this out in a couple of months.

**Comment by gijzelaerr** [comment]
lsmtool now also has python3 support https://github.com/darafferty/LSMTool/issues/10

**Comment by gijzelaerr** [comment]
This is a bit more complex since the packages need to build twice, one time for each interpreter. This would be easier if the LOFAR package didn't require a fixed build path.

**Comment by jamiefarnes** [comment]
Thank you so much for looking into this Gijs. Sorry to hear that it is more complex. I am hopeful that it is possible that @tammojan may potentially know a way to avoid a fixed build path...

**Comment by tammojan** [comment]
I'm not sure what @gijzelaerr means with the fixed build path. In the Lofar installation, [PythonInstall](https://svn.astron.nl/viewvc/LOFAR/trunk/CMake/PythonInstall.cmake?view=markup) does search for the platform specific install location; I'd be happy to patch that file if you can tell me what the behavior should be.

**Comment by gijzelaerr** [comment]
the LOFAR build system expects a specific build path, like `build/gnu_opt`. 

I need to do 2 builds, each for one python version. maybe I should try `python2/builld/gnu_opt` or `python3/build_gnu_opt`.

**Comment by tammojan** [comment]
The LOFAR build system indeed requires a specific prefix, `build` is not necessary anymore, only the last directory matters. Probably best to use `gnucxx11_opt` (and yes, both for python3 and python2).

**Comment by gijzelaerr** [comment]
ok trying. But still it probably doesn't work for everything, since some of the shared libraries are linked to a specific python.  So the only solutions are:

 * Port everything to Python3 (never going to happen probably) and drop python2
 * Switch to a system like casacore where there are multiple shared libraries per python
 * Don't support Python 3

**Comment by tammojan** [comment]
The linking with  specific python versions probably happens through boost-python so the same approach as casacore should work there.

**Comment by gijzelaerr** [comment]
it is not trivial to do, i'm not doing it unpaid :)

**Comment by gijzelaerr** [comment]
how do I specify/override which python interpreter to use for LOFAR

**Comment by tammojan** [comment]
The findpython.cmake in lofar is the same as the one used in casacore, so I think (hope) the mechanism from casacore can be used almost literally.

**Comment by gijzelaerr** [comment]
```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.5", minimum required is "2.6")
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.5")
-- Could NOT find PYTHON_PSYCOPG2 (missing: PYTHON_PSYCOPG2)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PYTHON_XMLRUNNER (missing: PYTHON_XMLRUNNER)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindPythonModule.cmake:97 (find_package_handle_standard_args)
  CEP/Pipeline/framework/CMakeLists.txt:6 (find_python_module)
```
i had to make a python3 version of the xmlrunner package, but that doesnt seem to help (but I can import xmlrunner)
```
$  python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlrunner
```

**Comment by gijzelaerr** [comment]
active working branch https://github.com/kernsuite-debian/lofar/tree/python3

@jamiefarnes  any suggestions are welcome, how did you get it to work?

**Comment by jamiefarnes** [comment]
Hi Gijs,

I was installing on High Sierra, which may have changed a few details. All I did was:
mkdir ../LOFAR-build/clang_opt
cd ../LOFAR-build/clang_opt

cmake -DBUILD_PACKAGES=pystationresponse ../../LOFAR-trunk/ -DUSE_OPENMP=OFF -DBoost_PYTHON_LIBRARY_RELEASE=/usr/local/lib/libboost_python3.dylib -DUSE_THREADS=OFF -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -DBoost_PYTHON_LIBRARY_DEBUG=/usr/local/lib/libboost_python3.dylib -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib -DPYTHON_Boost_LIBRARIES=/usr/local/Cellar/boost-python/1.65.1/lib/libboost_python3.dylib -DPYTHON_Boost_LIBRARY=/usr/local/Cellar/boost-python/1.65.1/lib/libboost_python3.dylib

make -j 4
make -j 4 install

If you need any more details, then please don't hesitate to let me know.
All the best,
Jamie

**Comment by gijzelaerr** [comment]
@tammojan any idea why lofar cant find xmlrunner when using python3?

**Comment by tammojan** [comment]
No I don't. The FindPythonModule.cmake script just executes `COMMAND "${PYTHON_EXECUTABLE}" "-c" "${_cmd}"`; did you change `$PYTHON_EXECUTABLE` for python 3?

**Comment by gijzelaerr** [comment]
yep

**Comment by gijzelaerr** [comment]
also it can't find psycopg2 while that is installed for python3. I guess the module finding logic is broken for Python3.

**Comment by tammojan** [comment]
Can you share your work so far so I can try to figure out where it's broken?

**Comment by gijzelaerr** [comment]
see comment above, there is a python3 branch for the package. In case you are not familiar with debian pacakges, this is the build dependency list:

https://github.com/kernsuite-debian/lofar/blob/python3/debian/control#L5

and this is the build call:

https://github.com/kernsuite-debian/lofar/blob/python3/debian/rules#L7

**Comment by tammojan** [comment]
Duh. The FindPythonModule uses a print statement without brackets. Trying to fix that.

**Comment by tammojan** [comment]
Should be fixed (upstream) in [r39597](https://svn.astron.nl/viewvc/LOFAR/trunk/CMake/FindPythonModule.cmake?r1=39597&r2=39596&pathrev=39597):
```diff
diff --git a/CMake/FindPythonModule.cmake b/CMake/FindPythonModule.cmake
index 650f897..8c81453 100644
--- a/CMake/FindPythonModule.cmake
+++ b/CMake/FindPythonModule.cmake
@@ -75,7 +75,7 @@ function(find_python_module _module)
     # Try to import the python module we need to find, and get its file path.
     if(PYTHON_EXECUTABLE)
       set(ENV{PYTHONPATH} ${PYTHON_${_MODULE}_FIND_HINTS}:$ENV{PYTHONPATH})
-      set(_cmd "import ${_module}; print ${_module}.__file__")
+      set(_cmd "from __future__ import print_function; import ${_module}; print(${_module}.__file__)")
       execute_process(
         COMMAND "${PYTHON_EXECUTABLE}" "-c" "${_cmd}"
         RESULT_VARIABLE _result
```

**Comment by gijzelaerr** [comment]
I think @jamiefarnes  used a small subset of the LOFAR suite, since I'm getting much more errors related to pytthon3 incompatibility:

```
/packaging/kern/packaging/build/lofar/build_python2/gnucxx11_opt/include/pytools/PycBasicData.h:280:18: error: ‘PyInt_Check’ was not declared in this scope                                                                       
    || PyInt_Check(obj_ptr)
       ~~~~~~~~~~~^~~~~~~~~
/packaging/kern/packaging/build/lofar/build_python2/gnucxx11_opt/include/pytools/PycBasicData.h:280:18: note: suggested alternative: ‘PySet_Check’
    || PyInt_Check(obj_ptr)
       ~~~~~~~~~~~^~~~~~~~~
       PySet_Check
/packaging/kern/packaging/build/lofar/build_python2/gnucxx11_opt/include/pytools/PycBasicData.h:284:21: error: ‘PyString_Check’ was not declared in this scope
    || PyString_Check(obj_ptr)) {
       ~~~~~~~~~~~~~~^~~~~~~~~
/packaging/kern/packaging/build/lofar/build_python2/gnucxx11_opt/include/pytools/PycBasicData.h:284:21: note: suggested alternative: ‘PyMapping_Check’
```

**Comment by tammojan** [comment]
I assume you already got it to link with the right boost-python.

This is indeed not python3-compatible; `PyIntCheck` and `PyStringCheck` don't exist anymore in python3 (in favor of `PyLongCheck` and `PyUnicodeCheck`). We'll have to place some `#ifdef`s around this code. Working on it.

**Comment by gijzelaerr** [comment]
awesome. You can use casacore and python-casacore as an example, i've done the same there.

That said, it would help if you make a separate so for every library that is linked against python. That way the Python2 and Python3 code can coexist next to each other. But maybe that is getting a bit out of scope.

**Comment by tammojan** [comment]
That is out of scope for now; I'm trying to get it running with either python3 or python2.

**Comment by gijzelaerr** [comment]
cool. I think I can make the package in such a way that it might work, but then you can't install the python3 and python2 bindings at the same time. This is not going to happen for KERN-4 though.

**Comment by tammojan** [comment]
I have a branch with fixes; not merged to the LOFAR trunk yet. The branch is at https://svn.astron.nl/LOFAR/branches/LOFAR-Python3-Task11556

To test this, build with `-DPYTHON_EXECUTABLE=/usr/bin/python3`. You'll need a boost-python3, which is installed by default on Ubuntu 18.04, possibly also on 16.04. Also, you'll need casacore built with `-DBUILD_PYTHON3=True` (it's false by default).

**Comment by tammojan** [comment]
Actually making a separate so for python2 and python3 should already happen because the so's get placed inside the python module directory (e.g. lib/python2.7/site-packages or lib/python3.6/site-packages). There are also python related so's in the `lib` directory, which I think can be ignored.

**Comment by tammojan** [comment]
For reference, the branch with python3 bindings has been merged on the trunk now.

**Comment by gijzelaerr** [comment]
you are the gandhi of radio astronomy

**Comment by gijzelaerr** [comment]
@tammojan the fix you committed upstream (r39597) is not in 3.1.5.

If I manually apply the patch I still get:
```
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.5")
-- Could NOT find PYTHON_PSYCOPG2 (missing: PYTHON_PSYCOPG2)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PYTHON_XMLRUNNER (missing: PYTHON_XMLRUNNER)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindPythonModule.cmake:97 (find_package_handle_standard_args)
  CEP/Pipeline/framework/CMakeLists.txt:6 (find_python_module)
```

**Comment by gijzelaerr** [comment]
@tammojan did this land in the main branch?

**Comment by gijzelaerr** [comment]
i think it is too much work to support both py2 and py3 at the same time, and the lofar package is going to be deprecated at some point. I think it is just best to not waste time on this anymore.

**Comment by tammojan** [comment]
Agree with you here; the python2 + python3 effort is being picked up by Astron, but is taking some time. The offline packages that should land in KERN are slowly moving away from the main LOFAR repo.
