### ISSUE TITLE
difmap inclusion request

### ISSUE THREAD

**Issue by sabourke** [kernsuite/packaging#98]
Packaged here: https://github.com/sabourke/difmap
Built and tested on xenial, bionic.

**Comment by sabourke** [comment]
help files get installed in /usr/share/lib/difmap because they're used by the binary and can not be compressed. dh will compress the bigger ones automatically if they go in /usr/share/doc

**Comment by sabourke** [comment]
Opps, changing usr/share/lib/difmap to usr/share/difmap

**Comment by gijzelaerr** [comment]
whoa! I didn't know you could list multiple distro versions in the same changelog entry!! ha! That saves me a lot of fiddling, thanks! No double thanks!

uploaded to KERN-3 and KERN-dev

**Comment by gijzelaerr** [comment]
unfortunatly luanchpad doesn't like it:
```
Rejected:
Unable to find distroseries: xenial bionic
Further error processing not possible because of a critical previous error.

difmap (2.4l-1kern1) xenial bionic; urgency=medium

  * Initial package
```
